### ISSUE TITLE
Add option to move an item from one collection to another

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#1054]
(This came up in discussions of Fedora datastream editing in Argo.)

There are use cases for moving self-deposited items from one collection to another. Someone could start by depositing in the Stanford Research Data collection and then later start a collection for their lab.

In the Hydrus-based system, changing a collection can only be done by editing the RELS-EXT datastream to change the APO and collection relationships. It can't be done in the Argo GUI. Even if it could be done in Argo without directly editing a datastream, any change made there would be overwritten if it's not made in H2. 

A cleaner way of making this change would be to make it in H2. The change would then need to be sent to SDR so that the Purl is updated.

**Comment by amyehodge** [comment]
I recall discussing this back in the planning stages, but I can't find it specifically called out in the feature list. I suspect it was part of our discussion of making hydrus objects look like DOR objects. But the ability to move something between H2 collections via H2 would seem to be an easier subset of being able to move any item to any other collection.

We would need to consider that when an item is moved from one H2 collection to another, it may have settings that will not match the new collection -- it may have the embargo date set to far out, or maybe the new collection doesn't allow embargoes at all, or it has a license assigned that doesn't match the new required license, etc. We would need some UI work to allow for users to verify changes to these things before moving the item. Or we would need to allow for that mismatch -- and then maybe require updates on versioning? Or not?

We would also need to consider whether this is something a depositor could do, if they have access to two collections, say. Or is it something only managers of collections to do when they manage multiple collections? Could a depositor propose a move and then have it approved by the manager (of the new collection? the old collection? both?). Many questions here.

**Comment by amyehodge** [comment]
This would be a great addition to our ADMIN ONLY functions. Issues to be resolved:
1. How to alert the admin that settings for the item don't match the settings for the new collection. I believe this to be the full list of things that need to be assessed for conflict:
- item has an embargo date but the collection does not allow embargoes
- item has an embargo date farther out than the collection allows (e.g. collection requires no more than 6 months for embargo and user has selected 3 years)
- item has a visibility setting that does not match what the collection allows (e.g. collection requires "world" but user has chosen "stanford only")
- item has a license that the collection does not allow (e.g. collection requires CC-BY-4.0 and user has selected CC-BY-NC-ND-4.0)
- Item may not have a DOI but the collection requires it
-- note that if the item has a DOI but the collection doesn't allow that, that conflict will have to stand as we can't undo a DOI 
2. How to handle these conflicts:
- once conflicts are known, admin contacts content owner to ask how they want them resolved. UI would include an option to update these in the process of moving to the new collection.
- allow conflicts to exist but require content owner to update them if they version the item
- allow conflicts to exist indefinitely (I'm not sure if the app can easily support this, or that this would meet with collection manager expectations)

**Comment by amyehodge** [comment]
Also, we should restrict the moving of items to only those collections have been completely deposited at least once. This corresponds with how the app works for normal deposits, where you have to deposit the collection before you can create the first item in it.

**Comment by amyehodge** [comment]
@jcoyne Proposed mockups from Astrid.

Item view page with "move to another collection" selected.
<img width="673" alt="image (4)" src="https://user-images.githubusercontent.com/5558511/185654384-b58ad708-8fab-46fc-b8bd-524ce97e7e16.png">

The drop-down menu would have all the collections that have been deposited at some point. Collections in a version draft state are also fine, just not the first draft state.

Type-ahead would be nice for this drop-down since there are many collections, but another option is to have the selector move to the "S" part of the list when the user types an "S", etc.

Once the user has chosen a collection, a check would run to compare the current item settings with the current collection settings. The results would output as a table that we could review. This is what it would look like if everything is good and there are no conflicts:
<img width="673" alt="image (5)" src="https://user-images.githubusercontent.com/5558511/185655018-4107ef02-bc3d-4788-ae16-188d71749093.png">

The user could then click the "Move" button to complete the task.

If there are conflicts, the user is presented with the edit pencil icons that will take them to the section of the item edit form that will allow the admin to adjust these to match up with the new collection.
The "Move" button is greyed out until conflicts are resolved.
<img width="673" alt="image (6)" src="https://user-images.githubusercontent.com/5558511/185655308-98ee0f32-bba1-47e6-a96a-78e95d4a7034.png">

I will be talking with Hannah early next week re: policies regarding some of the conflicts mentioned in the comment above so we can determine if there are cases (and I think there are) where we would need to let the conflicts persist. If this is the case, we likely won't grey out the "Move" button when there are conflicts. We can then also discuss what technical implications there may be to allowing certain conflicts to remain once the item is moved.

**Comment by andrewjbtw** [comment]
Based on the Argo experience, I recommend including the collection druid along with the collection title in the dropdown menu as a way to make it easier to distinguish between similarly named collections. If I understand the constraints correctly, there should always be a collection druid when this menu is used because of the requirement that collections have at least one version before they can contain items.

**Comment by amyehodge** [comment]
@andrewjbtw yes, true, there should always be a druid for these cases.

**Comment by amyehodge** [comment]
replaced by #2685
