### ISSUE TITLE
Give hfrost admin permissions in H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1169]
Hannah needs to be able to see everything.

**Comment by jcoyne** [comment]
Amy indicated that Hannah is already a member of the admin group, so the problem here is that Hannah is not seeing the "All Collections" table.  This is only show to members of that group, so it's likely that the groups are not being set correctly for Hannah.  We may need a developer to add some logging around this code and see what is going on:
```
https://github.com/sul-dlss/happy-heron/blob/5ddeb9434aeb8eadf4c8ad1c53e68d6af5e6f408/app/controllers/application_controller.rb#L35-L48
```

**Comment by amyehodge** [comment]
solved with a logout/login
