### ISSUE TITLE
Reserve a PURL

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1248]
This is still not working.

**Comment by jmartin-sul** [comment]
I've done some testing and am a bit stumped at the moment.  I wonder if there's some flakiness with communication between  SDR (specifically... dor-services-app?  sdr-api?) and H2?  Or some flakiness in H2 job execution?

I tried to reserve a PURL at 10:28 am pacific today, and that seemed to get stuck in the "Reserving PURL" state (still stuck as of this comment, see screenshot).  But subsequent attempts to reserve a PURL all seemed to succeed.

Because of the timing (10:28 am), I suspected this sdr-api error reported by Honeybadger, but I think it's a red herring:  https://app.honeybadger.io/projects/67994/faults/64639563/01EZWNHS132M1NPG4NRWVQD9G1?page=0#notice-params

```
Dor::Services::Client::UnexpectedResponse: Bad Request: 400 ({"errors":[{"status":"400","title":"Bad Request","detail":"Unable to find collection: 'Unable to find 'druid:mp757fq0674' in fedora. See logger for details.'"}]})
```

I suspected maybe a race condition, where the collection I'd just created couldn't be referenced yet, but the collection in the error message is `mp757fq0674`, and the collection for the stuck purl res is `kr811mj1951`.  The couple of errors I see in dor-indexing-app from around the same time (10:40 am) seem to be about a data error (attempted reindexing hitting an object without a title).

The other thing I noticed was that a PURL reservation I successfully completed got stuck on "Deposit in progress" after I edited metadata and tried to deposit.  I reserved that PURL as fast as I could in a newly created collection, trying to reproduce the stuck reservation by creating the race condition I'd initially thought might be the culprit, but I was able to choose a type and edit metadata without a problem.

The last thing I noticed is that the PURL link worked for all my test reservations, _except_ for the stuck reservation.  I can visit Argo for all of the druids.  The stuck one only has `registrationWF`, whereas the rest have that plus `preservationIngestWF` and `accessionWF`.
<img width="1411" alt="Screen Shot 2021-03-03 at 3 47 44 PM" src="https://user-images.githubusercontent.com/7741604/109894688-ca616b80-7c42-11eb-985f-5a45c02ebe8b.png">

No other obvious errors jumped out at me from Honeybadger.

After typing all that out, the only somewhat concrete hunch I have is something something stale worker code?  Since there was a fix to the accessioning flag in sdr-client? 🤷

**Comment by jmartin-sul** [comment]
https://github.com/sul-dlss/happy-heron/pull/1261 got druid reservation working

https://github.com/sul-dlss/sdr-api/pull/285 should fix things so that content can be accessioned to the SDR object when attempting to turn the H2 work for the PURL res into a real deposit

the last lingering issue that i know of is that when the PURL is initially reserved (when it's still just a v1 Registered SDR object with no accessioned files) the PURL link for the druid returns a 404 not found.  this goes away once the H2 work is turned into a real deposit, though i suspect the current behavior is not adequate to consider the feature done.

**Comment by andrewjbtw** [comment]
"Registered" is supposed to not have a Purl and we guard against publishing registered objects. If the goal here is to have a live Purl, it would need to be accessioned. But if the goal is get the druid that will be used to make the Purl, so that the depositor knows what the citable URL be when the Purl goes live, then this is to be expected.

**Comment by amyehodge** [comment]
The goal is definitely to get the druid that will be used to make the PURL so that the depositor knows what the citable URL will be when the PURL goes live. The 404 in the meantime is not a problem IMO.

**Comment by jmartin-sul** [comment]
ah, well, in that case... maybe this ticket can be closed, pending successful testing by @amyehodge?  the sdr-api change should now be live on -qa and -stage servers, and i was able to reserve a PURL and turn it into a real accessioned deposit when i tested on -qa last night.

**Comment by amyehodge** [comment]
@jmartin-sul I just tested this and was able to 1) successfully reserve a PURL, 2) later edit that PURL and deposit it and 3) have that deposit appear to complete properly.

However, I was never given the option to choose a work type. Upon editing this reserved PURL I expected to have the work type module pop up first so that I could do that. Now that it is deposited, the work type says "purl_reservation" and -- as intended -- there is no way to edit this. That seems to be the one lingering thing not working properly here. Looking good!

**Comment by jmartin-sul** [comment]
@amyehodge that's very surprising to me!  forced type selection was one of the first things about PURL reservation that i got working consistently, and i can't remember any testing in the last few weeks where it hasn't worked as expected for me.  i actually just tested it successfully (afaict) on stage a few moments ago, and it worked as expected in my testing on qa last night, when i was trying to get deposit working.

would you mind trying again?  i'm grasping at straws here, but you might try doing a force refresh (cmd+shift+R) on the H2 dashboard before you try again (something something stale javascript 🤷).

if it fails again for you on retry, or if you already tried the force refresh thing, maybe we can hop on zoom and i can see what you're doing, just to make sure i'm not missing something about either the expected behavior or the particular interaction in this case?

**Comment by amyehodge** [comment]
With a few specific exceptions for which I will file separate tickets, this work is complete at this point. Nothing further needs to be done for beta testing, @jmartin-sul .
