### ISSUE TITLE
List subtype options in the work type modal in columns from top to bottom instead of left to right.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1334]
This applies to both the short lists and the larger list displayed when the user clicks on "see more options"

**Comment by jcoyne** [comment]
I'm not aware of a way to put these in balanced columns without constraining the height of the container they appear in.  This is challenging since each list is of a different size. Accessibility is also a concern. We want it to display in the correct reading order for people who use screen readers.  We have the additional concern that it must responsive to smaller screens.  Here you can see we are collapsing the list for mobile devices:

 ![Screen Shot 2021-05-18 at 10.27.48 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/e64018cc-6fa6-4af0-b0aa-28c1cb4e473f)

**Comment by jcoyne** [comment]
FWIW, I tried switching to CSS columns, but then the checkbox was not displaying in the third coumn: ![Screen Shot 2021-05-18 at 10.41.46 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/0fd9ad75-2e6f-4c59-b9ae-9280573a531c)
