### ISSUE TITLE
Display embargo release info in history table for item

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1347]
Vivian asked me to check on the status of objects in Argo to see if things look correct.
 
druid:jw479gt3012, https://sul-h2-stage.stanford.edu/works/13246
Argo shows v3 accessioned while H2 shows it is on version 2. The v3 appears to be an embargo release that is not recorded in H2.
 
druid:gy649yx4586, https://sul-h2-stage.stanford.edu/works/13311
This item does not show up in Argo at all. I get a “page you are looking for does not exist” error.
 
Otherwise, the version number and status seems correct. Note that everything I looked at was “Accessioned” because items don’t have PURLs to look up in Argo until they are deposited, and versioning isn’t currently working as noted above, so nothing can be “v2 open”.

**Comment by jcoyne** [comment]
Do we want the h2 version to be identical to the Argo version? Can you explain why that is important? Could it be confusing to the user that they only made 2 versions in h2, but now there are 3 versions?

**Comment by amyehodge** [comment]
I personally think this would be confusing, but suspect that any SUL user who might check on their content via Argo would find it confusing for the version in Argo not to be reflected in Hydrus as well. And, in this particular case, I would think any user would want to see the embargo release in the history as well. 

@hannahfrost I'd like your thoughts. I'm now thinking that sometimes content is versioned for administrative reasons in Argo (by @andrewjbtw , via some bulk action, etc -- I usually don't know why these are happening) and we may not want to reflect those back in H2.

And to be clear, I'm not saying that the version number reflected in H2 necessarily needs to match the version number Argo -- Hydrus and Argo version numbers don't match now, I don't think. I'm saying if there are three versions in Argo I would think we would show 3 versions in H2 and the history information should display the "what's changing" comment or the comment entered in Argo when versioning.

**Comment by andrewjbtw** [comment]
I believe what Hydrus and Argo do now are not in sync from the user perspective, but are in sync from the data perspective. In the versionMetadata, there's both a `tag` and a `versionId`. 

```xml
  <version tag="7.0.0" versionId="14">
```
Hydrus shows the version number as the `tag` value and Argo shows the number from the `versionId`. So the two systems are drawing from the same data but applying it in different ways.

I think there was an assumption/expectation that people would carefully apply semantic versioning, and only "major" changes actually increment that first value in the `tag` number. That may be why Hydrus bases its version number display on the tag. Meanwhile, the `versionId` serves as a count of all versions regardless of whether they're considered major, minor, or admin, and for Argo it makes some sense to show this number as Argo is for administrative management. Or maybe different people implemented the two displays and didn't share notes. 

In practice, it's hard to say there's consistency across the SDR with respect to semantic versioning, and I wouldn't trust that a "major" version is actually major, which makes it hard to say what H2 should actually display if something got an Argo-made version.

In any case, the current state is:

- Hydrus and Argo show different numbers if the semantic versioning differs from the raw version count
- the Hydrus history list doesn't include Argo-made changes, 
- but Hydrus does read the same versionMetadata datastream as Argo, so it's aware of the Argo changes to the extent that it writes the correct `tag` and `versionId` for each new version

This is a good example of a multiply-versioned item where Argo and Hydrus show different version numbers because of the divergence in major/minor versions. In the Hydrus event history, you can see Hydrus doesn't record all of the Argo-made versions (no version 3 or 4.1.0, both of which were descMD refresh).
Argo: https://argo.stanford.edu/view/gb129dk1428
Hydrus: https://sdr.stanford.edu/items/druid:gb129dk1428

With respect to embargo release, I think H2 should show the embargo has been released, but if I didn't work with SDR I wouldn't think embargo release created a new version, as no content or metadata is changing. It's only a versioning event in SDR because the SDR object model makes it that way: SDR includes visibility settings in the data that makes up a version, so if you change those settings you have to make a new version.

**Comment by amyehodge** [comment]
@andrewjbtw Thanks for this thorough explanation of this. Users have frequently been confused about when to use the "major" vs. "minor" options in Hydrus, which is why we have done away with that in H2 in favor of just logging a new version. 

I think we should continue not to show Argo-made changes in the H2 history. 

I would like to see the embargo release reflected in the history in some fashion, whether it looks like a new version or not, for clarity to the users.

**Comment by hannahfrost** [comment]
@amyehodge I am glad that we are doing away with the major/minor versions in H2 to reduce user confusion. I agree that we should not show Argo-made changes in the H2 history. 

And I agree that embargo release should be reflected and displayed in the H2 history because it is a key event in the life of an object. In thinking about changes to embargoes on H2 items - must we make sure these are always done in H2 and never in Argo?

**Comment by amyehodge** [comment]
I am changing the name of this ticket from "Address status differences between H2 and Argo" to "Display embargo release info in history table for item."

**Comment by jcoyne** [comment]
This requires dor-services-app to post a rabbitMQ message when it releases the embargo and a corresponding job in h2 to listen for that event and record a message in the log.
