### ISSUE TITLE
Blue info icon is not in alignment

### ISSUE THREAD

**Issue by astridu** [sul-dlss/happy-heron#1515]
The blue info icon should be next to the field label. It is wrapping to the next line. Thank you!

![image](https://user-images.githubusercontent.com/42216982/119192389-f10a9380-ba34-11eb-9d97-832cd48bfb82.png)

**Comment by jcoyne** [comment]
![Screen Shot 2021-05-24 at 4.51.22 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/49362d46-f8e2-4b6b-b219-8bbbcf1b6a07)

@astridu it does line up if you make the viewport wide enough.  The problem here is that if we give this label more columns in the grid layout, then the field will not align with the widgets above (depositors, managers, notification settings).

**Comment by astridu** [comment]
Ok, no worries. I'll close this.

**Comment by astridu** [comment]
.
