### ISSUE TITLE
display of file upload errors 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/happy-heron#1577]
Current behavior for a file upload error:

![image](https://user-images.githubusercontent.com/96775/120683128-1abeb400-c452-11eb-87cf-985249d8b786.png)

There is no filename showing, and I'm sure this isn't the optimal display.

While working on #1378, I had upload errors looking like this:

![image](https://user-images.githubusercontent.com/96775/120565208-68d7a700-c3c1-11eb-9f32-0132826f2481.png)

@amyehodge is okay with the above.

Certainly we will want the filename to display, and I would suspect an error symbol in addition to the error message.   I took the default dropzone behavior and styled it a bit to get the above.

However, when I rebased my work on main, the `.on("error"` method had been added to `dropzone_controller.js`.   I started down this path:

![image](https://user-images.githubusercontent.com/96775/120683980-12b34400-c453-11eb-80d2-07787211e8ce.png)

and it was suggested by JCoyne that I split out the error handling from the success checkmark work in PR #1576.

For developers:
The way I've been able to force an upload error is to add this code around line 115 in the `dropzone_controller.js` file:

```
    this.dropZone.on("success", file => {
      file.controller.emitDropzoneError('this is a very long upload error asfasfasf asfasfasfsaf safasfsafs afsfsfsafa')
    })
```

And then in `file_row_component.html.erb` you will need to comment out the div with class `dz-success-mark` so you don't have both the success and error displays at the same time.

**Comment by ndushay** [comment]
more hints for the developer:
![image](https://user-images.githubusercontent.com/96775/120691437-4eeaa280-c45b-11eb-8f97-aeef47922d29.png)

![image](https://user-images.githubusercontent.com/96775/120691462-56aa4700-c45b-11eb-9940-1d5b2b1a3794.png)

**Comment by amyehodge** [comment]
@astridu  Could you provide us with some help on this one? 

The current display of the file upload error message is next to the "Choose file" button, which isn't a great location if you've just dragged over 30 files to upload and one of them fails. Especially since the message here doesn't include the filename. 

Better, I think, is the other example Naomi has with the error by the file that has failed. And for it to include the filename (as a double-check). 

However, Naomi points out that when the upload fails, we have a lot of UI elements that are kind of confusing and don't apply to a failed upload -- like the green progress bar and the "Description" text and box.

Can you suggest a way for us to display the file upload error in a clean way? And what should the user interaction then be for a failed file -- should they have to click the trash can icon or something? There is currently no obvious action to take. Thanks!

**Comment by astridu** [comment]
How about something like this. We replace the thumbnail with the error icon, remove the progress bar and place the error message below the file name?

![image](https://user-images.githubusercontent.com/42216982/120846903-a1919080-c527-11eb-967c-0a9603ec6c6e.png)

**Comment by amyehodge** [comment]
@astridu This feels much better to me. @ndushay and @jcoyne -- do you think this adequately addresses all the issues here?

**Comment by jcoyne** [comment]
@astridu do we still need the Description and checkbox if there's an error?

**Comment by astridu** [comment]
Good point. I guess not. Here's what it could look like w/o those two fields. 
![image](https://user-images.githubusercontent.com/42216982/125342332-a0fbcf00-e309-11eb-94d8-f037632e2b9f.png)

**Comment by amyehodge** [comment]
@astridu This mockup makes a lot more sense to me. Thanks.

**Comment by amyehodge** [comment]
@jcoyne Can we put this one in the ready? It looks good to me.
