### ISSUE TITLE
Provide method to retry stalled deposits that could be fixed by re-sending the same request

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/happy-heron#1585]
Under some circumstances, deposits fail in a way that should be fixable by re-trying the deposit attempt after the underlying cause of the failure has been resolved. I'm thinking specifically of situations where a deposit has failed before any accessioning has begun to make the new version of the object.

For example, this deposit was stopped by a cocina model version mismatch: https://sul-h2-stage.stanford.edu/works/17407 Now that the mismatch has been resolved, it should be deposit-able except I don't see a way to retry it. There should be an official or semi-official way to retry it, as we're likely to run into this class of issues in the future and I'm not sure what we'd do to fix this item if it happened in production.

In terms of the UI, I'm in favor of what can be done given our time constraints to make retries possible during the first/limited release. It might be best to have a retry option in the web application, but even a way to retry from the command line or the ruby console would be a help.

If the option is in the web application, I leave it open whether it should be an available to administrators only or to also make it available to the depositor. Another possibility would be if the application could show an error in this situation and ask the user to try later, without turning off the ability to edit or submit the form. In that case, there wouldn't be a retry button, just the same deposit button to be pressed later.

**Comment by amyehodge** [comment]
@andrewjbtw If the fixes in such cases will require manual intervention and/or may take some time resolve themselves without intervention, I don't think adding a button for all users is going to be useful. They will just click it immediately and repeatedly and if not successful in 30 seconds, will give up. It makes more sense to me to provide some kind of message to contact us so that we can intervene and then click a button visible only to admins and/or run the process from the CL.

**Comment by jcoyne** [comment]
We are adding automatic retry in https://github.com/sul-dlss/happy-heron/pull/1593 which should obviate the need for a manual retry.
