### ISSUE TITLE
Discarding Work Version in PURL Reserved state causes Error

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/happy-heron#1598]
When a work version is in `purl_reserved` state and the **Discard draft** button is click, re-routing to the dashboard causes the following HoneyBadger error: https://app.honeybadger.io/projects/77112/faults/76781151.

**Comment by jcoyne** [comment]
I'm not sure one should be able to discard a registered purl, because we have no way of de-registering a PURL.   I'd like @amyehodge and @andrewjbtw  to weigh in on how we ought to resolve this.

**Comment by amyehodge** [comment]
@jcoyne @jermnelson @andrewjbtw We have always allowed users to discard registered items in Hydrus. This seems equivalent to me. Users then no longer see these items in the application. However, I'm not clear on what happens to them on the back end, since they already have a druid assigned. Andrew would need to speak to that. 

But, in short, yes, people will change their minds about needing these sometimes, and we want them to be able to clear them out of H2, whatever that means on the back end.

**Comment by jcoyne** [comment]
> we want them to be able to clear them out of H2

Why do people want to clear them out? Won't they just use what they've already registered next time they need a druid?

**Comment by andrewjbtw** [comment]
A reserved Purl isn't a purl yet, it's just a registered druid. On the SDR/Fedora side, discarding it is the equivalent to purge. I think in Hydrus, discarding also must have had the extra steps of clearing the Hydrus index and the data folder on the hydrus filesystem if any files had been uploaded before the discard.

**Comment by jcoyne** [comment]
Apologies, I've been  using the wrong terminology.  We have no way to unregister a druid.  Do we want to create a bunch of druids that are never used yet we still have to keep track of?

**Comment by amyehodge** [comment]
> Why do people want to clear them out? Won't they just use what they've already registered next time they need a druid?

I actually laughed out loud at this. This has not been our experience.
