### ISSUE TITLE
Sorting of collection deposits table by modified date not working correctly

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1675]
When I try to sort the collection details table for https://sul-h2-stage.stanford.edu/collections/1103/works by modified date I get these two displays, presumably one for most recent to oldest and one for oldest to most recent. But neither of them look right.
![Screen Shot 2021-06-18 at 2.33.02 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/6397e93c-32e8-4277-b7c4-05b112ba9776)

![Screen Shot 2021-06-18 at 2.33.12 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/7c605f88-fcfb-4f13-a758-67344e50cb86)

**Comment by aaron-collier** [comment]
@amyehodge I'm pretty sure this is because DataTable is default sorting by string. In order to date sort, especially in the format we're displaying, will require a plugin. From what I can tell, the currently available plugins require jQuery, which we've tried to avoid including.

The easiest option would be to format the data in an easily sortable way (i..e YYYY-MM-DD for example).

cc: @jcoyne in order to raise the issue of including jquery (or if you have any pointers here).

Thanks.

**Comment by jcoyne** [comment]
@aaron-collier our requirements here are going beyond off the shelf libraries, let's just build our own.

**Comment by aaron-collier** [comment]
@jcoyne I'll kick this back to ready then, With STLP this week I don't want to hold this up from anyone else.
