### ISSUE TITLE
Two deposited items are in limbo in Argo

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1744]
Greta has identified an issue with two H2 deposits when she tries to do the usual cataloging on them in Argo post-deposit.

Both hg666vd0263 and gj834gp4151 are showing both the "Close version" and "Open for modification" options grayed out in Argo, so she can't do anything.

**Comment by amyehodge** [comment]
From Greta:
![Screen Shot 2021-07-01 at 8.04.31 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/ffe6b229-ef42-4fd5-a6ac-a5961f30b327)

![Screen Shot 2021-07-01 at 8.04.40 PM.png](https://images.zenhubusercontent.com/5e9e06e81c23039800e23efc/e2688591-b7ab-4599-8dd7-eedeb0e30296)

**Comment by andrewjbtw** [comment]
I think these are one-time issues related to still open Hydrus workflows left behind by the migration. Since these druids were migrated and detached from Hydrus, the Hydrus workflows were never marked as completed. This blocks versioning because versioning requires the hydrusAssemblyWF to be complete. 

I've marked the Hydrus workflow as complete for both objects and the buttons are no longer grayed out. We'll need to identify this specific situation for other migrated objects. I think what will be safe to do is mark hydrusAssemblyWF steps complete for each successfully migrated druid. This situation will druids that are Registered or Opened at the time of migration. Accessioned druids should be ok.

**Comment by jcoyne** [comment]
@amyehodge is there more for us to do on this ticket or should it be closed?

**Comment by amyehodge** [comment]
@jcoyne Sounds like the work @andrewjbtw  noted to mark hydrusAssemblyWF as complete for the subset of migrated druids in Registered or Open states is something that needs to be done now. And we need to add this into the workflow for the full migration in a few weeks. Who will do those tasks, and do they need tickets?

The two items called out in this ticket have been taken care of.

**Comment by jcoyne** [comment]
@amyehodge will we be able to just mark all of the hydrusAssemblyWF processes as complete at that time?

**Comment by amyehodge** [comment]
@jcoyne That's a question for @andrewjbtw.

**Comment by andrewjbtw** [comment]
That should be ok. Marking the steps complete won't run anything and since they'll never be in Hydrus again it should be safe.

**Comment by jcoyne** [comment]
@amyehodge I updated #1718 to add that step, so I believe this can be closed.
