### ISSUE TITLE
Add yes/no text to DOI toggle on work edit form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#1938]
On the work edit form for the depositor selects option, it would be better if the toggle looked like the one for the auto-generated citation with the yes and no printed on it so it’s clearer what choice you’re making.

**Comment by jcoyne** [comment]
@astridu @amyehodge the problem is that the slider widget blends into the darker background:
<img width="154" alt="Screen Shot 2021-08-12 at 11 14 51 AM" src="https://user-images.githubusercontent.com/92044/129231722-5ce3bb8b-7aa3-4645-a298-b5aa3e9d0de9.png">
<img width="145" alt="Screen Shot 2021-08-12 at 11 14 46 AM" src="https://user-images.githubusercontent.com/92044/129231724-c69548f8-0c7b-44fc-9e68-82ec384d6b96.png">

**Comment by astridu** [comment]
Can you change the color of the 'No' widget to white? 
![image](https://user-images.githubusercontent.com/42216982/129260487-66804b25-3350-4d2b-a498-46f198119edc.png)

**Comment by jcoyne** [comment]
Yes, but that looks like you've also added borders too. What colors is the border?

**Comment by astridu** [comment]
border: 767674
fill: C0C0BF
TY!

**Comment by jcoyne** [comment]
What do you think of this:
<img width="134" alt="Screen Shot 2021-08-12 at 4 50 13 PM" src="https://user-images.githubusercontent.com/92044/129274684-0efbc416-de2b-4c5b-9c65-4202fb9a7f5b.png">
<img width="137" alt="Screen Shot 2021-08-12 at 4 50 08 PM" src="https://user-images.githubusercontent.com/92044/129274689-d868ee1d-ef82-4411-8aef-518977e4af96.png">

**Comment by amyehodge** [comment]
Works for me.
