### ISSUE TITLE
Remediate items where creation dates had a day or a month + day added to them that weren't entered by the user

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2086]
This is a follow-on to the work done in #2066.

We need to identify all H2 items that had a year for a creation date originally but then had a month and day added to them (by the now changed version of the H2 cocina generation code) when they were versioned. We need to remediate these to remove the month and day.

We will need someone on infra team to export the data for us. I think we'll want to see the data for all H2 items that now have a creation date of Jan. 1, [any year]. 

In the export for those items we'll want:

- item druid
- item title
- collection druid
- collection title
- creation date
- ???

@andrewjbtw can you check that this all seems right/complete before I get it put on the FR board? Thanks.

**Comment by amyehodge** [comment]
From Andrew: "It looks like we need to do a full descriptive metadata comparison between what’s stored in Fedora and what’s represented in H2, so that we identify fields where H2 will modify the data in Fedora the next time a version is sent, regardless of whether any edits are made to it."

**Comment by vivnwong** [comment]
@andrewjbtw @amyehodge, can you review the scripts added by Peter and let me know whether you can proceed to remediate the druids? or you need more developers' time.

**Comment by andrewjbtw** [comment]
This is still on my to do list but I will be working on it soon.

**Comment by jmartin-sul** [comment]
assigned to @andrewjbtw at @vivnwong's request

**Comment by amyehodge** [comment]
Making a note here to make sure we didn't send incorrect date information to DataCite for any of these items. This should only have been possible if the items were updated in H2 after they were migrated. And of course if they were assigned a DOI in H2.

**Comment by andrewjbtw** [comment]
I've finally finished the analysis on this one. I ended up following a bit of a different strategy than we discussed above because we've now migrated away from Fedora, allowing me to more easily parse the Cocina.

This is what I did:

1. Get a list of every druid with a "Project : H2" tag that has a date on the Purl that ends in either `-01` or `-01-01`. I did this by parsing the public Cocina published to the Purl. Hopefully, I did this correctly by piping the Cocina for each druid through `jq` with: 

```
jq '.description.event | .. | objects | .value'
```

This yielded about 500 druids. I chose this strategy because Peter's query above for H2 items that include only a year or year-month resulted in 3000 druids and it seemed easier to work with a smaller set.

2. I took the list of druids with dates ending in `-01` or `-01-01` and generated a CSV listing their dates as recorded in H2:

```ruby
CSV.open(output_file, 'wb') do |csv|
  CSV.foreach('tmp/date_remediation/druids.txt') do |row|
    druid=row.first
    work = Work.find_by(druid: druid)     
    work_version = work.head
    csv << [work.druid, work_version[:created_edtf]]
  end
end
```

3. I compared the two lists in a Google sheet, eliminating any druid where the H2 EDTF ended in `-01` or `01-01`. That left a total of 90 druids to fix.

This CSV contains the list of druids: [date-01-issues-h2.csv](https://github.com/sul-dlss/happy-heron/files/9570503/date-01-issues-h2.csv) There are multiple columns for the SDR date output because of the way I parsed the Cocina when there are multiple dates (as in a range)

There is one big caveat: while I made sure none of these druids have catkeys, indicating a SUL staff member updated it, I did not otherwise check if any of these items has been edited in Argo outside of H2. Some of these items may not need updating if an Argo-made update should be considered authoritative.

**Comment by amyehodge** [comment]
@andrewjbtw @jcoyne I have reviewed the 90 items in the spreadsheet. 80 of these should definitely be updated. As for the other 10:

**These are ones to definitely NOT update:**
hk947yx8059 | do not update (this is an item of mine that has already been updated
vj868kg9341 | do not update; made to stream -- I have locked this
wv398fc4383 | yes; pre-assembly reaccession, embargo released -- already locked

**These are ones I'd appreciate if @andrewjbtw could review.**
I suspect we should just lock and skip updating the two Lighting the Way items. The embargo release shouldn't be a problem, but I put it on this list to be sure.

bw050ff7565 | Argo has an extra version
mq184tk7726 | version 2 not matching + Argo has an extra version
nx655rf2881 | Argo has 5 extra versions; Lighting the Way
rt078dm2196 | Argo has 4 extra versions; Lighting the Way
sz403bn0186 | version 2 not matching + Argo has an extra version
yg491zk9073 | Argo has extra version
zf117dn1545 | embargo released

**Comment by andrewjbtw** [comment]
Agreed about the Lighting the Way items. For the other items, should we just update via Argo? It seems like most of them should still have the -01 dropped as far as the purl display goes, even if not edited in H2.

I find these three puzzling because their most recent versions have the sdr-api events that are associated with an H2 deposit, yet their H2 version numbers don't match. I wonder if they were items that had the deposit indicator spinning until someone modified them on the back end.

mq184tk7726 | version 2 not matching + Argo has an extra version
sz403bn0186 | version 2 not matching + Argo has an extra version
yg491zk9073 | Argo has extra version

**Comment by amyehodge** [comment]
I have locked the two for Lighting the Way. I agree that these oddball ones should just be updated in Argo by someone. I updated my comment above. I'm not sure I know exactly how to fix these.

**This one is maybe okay to leave on the list @andrewjbtw?** 
zf117dn1545 | embargo released
I'd prefer not to make it uneditable in H2 if we don't have to, and the embargo release, though a new version in Argo, shouldn't make it uneditable in H2, should it? (I hope not.)

**Comment by andrewjbtw** [comment]
Except for the one that has the embargo release, I'll do the Argo updates.

**Comment by ndushay** [comment]
slack conv:

![image](https://user-images.githubusercontent.com/96775/192892046-387e2cc8-9144-4a35-a18e-444fbce9e62e.png)

**Comment by jcoyne** [comment]
I grabbed these data on h2 using:
```
3.1.0 :099 > druids.map do |id|
3.1.0 :100 >   druid = "druid:#{id}"
3.1.0 :101 >   work = Work.find_by(druid:)
3.1.0 :102 >   [druid, work.head.created_edtf.edtf]
3.1.0 :103 > end
```

Then I pasted the data into DSA (only 80 rows) and ran:
```
3.1.0 :147 > data.each do |row|
3.1.0 :148 >   dro = Dro.find_by(external_identifier: row.first)
3.1.0 :149 >   dro.description.dig('event').find { |event| event.dig('type') == 'creation' }.dig('date', 0)['value'] =
row.second
3.1.0 :150 >   dro.save
3.1.0 :151 > end
```
to update them.
