### ISSUE TITLE
Deposits table for collections should sort by date

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2202]
Previous work on this sorting was done on #1675.

Sorting of these tables used to work, but now is not quite right. As an example, see https://sdr.stanford.edu/collections/59/works.

The default when the page loads should be to sort with most recent modified at the top, but on this collection there are three oddballs at the top that are out of order, then the rest of the list looks fine.

![Screen Shot 2022-03-25 at 3 47 44 PM](https://user-images.githubusercontent.com/5558511/160191715-f328d3dc-71e7-416c-a027-60515d2d3c07.png)

The same three appear out of order at the end of the list when sorting from oldest to newest:

![Screen Shot 2022-03-25 at 3 52 56 PM](https://user-images.githubusercontent.com/5558511/160191881-83518361-9d23-403b-b2bc-b5e64010bbd1.png)

For the large Stanford Research Data collection, the first 82 or so items appear to be completely out of order, then the list settles down into newest to oldest. See https://sdr.stanford.edu/collections/168/works (this list is too long to post a screenshot).

**Comment by amyehodge** [comment]
@hannahfrost

**Comment by andrewjbtw** [comment]
Another example, where it's the first 5 that are out of order. It's hard to see what the pattern is at first glance:
https://sdr.stanford.edu/collections/137/works

**Comment by edsu** [comment]
I can see that the works are coming back from the database in the correct order. Temporarily disabling [the use](https://github.com/sul-dlss/happy-heron/blob/f51a52c3e22990b77f7f9d3edfe04809b2c05d8f/app/components/collections/works_component.html.erb#L1) of [simple-datatables](https://www.npmjs.com/package/simple-datatables) shows the table correctly sorted. Here it is in my dev environment before and after disabling simple-datatables:

<img width="1405" alt="Screen Shot 2022-04-01 at 11 44 12 AM" src="https://user-images.githubusercontent.com/33829/161297497-addf8313-1237-432a-9b12-bb8f1fd96f95.png">

<img width="1405" alt="Screen Shot 2022-04-01 at 11 44 57 AM" src="https://user-images.githubusercontent.com/33829/161297524-4e7a6b79-bc36-4204-b6ec-a1dbe92c60d2.png">

See how 1-900-GOT-PURL sorts to the top correctly in the second? So I think the problem lies somewhere in our use of simple-datatables. I'll keep digging there.

**Comment by edsu** [comment]
I think what's happening here is that [time-elments](https://github.com/github/time-elements) and [simple-datatables](https://www.npmjs.com/package/simple-datatables) are running concurrently when the page renders, and simple-datatables is sorting a table that has had its dates partially transformed. I don't know what the solution is off the top of my head, but I will continue digging.

**Comment by edsu** [comment]
After going down the rabbit hole of [testing](https://codepen.io/edsu-the-decoder/pen/XWVzbEW) the table separately as HTML/JavaScript with simple-datatables.js I discovered that the format we were using was slightly off `MMM DD, YYYY` instead of `MM D, YYYY`. 

It looked like this sorting problem manifested in [all_collections_component.html.erb](https://github.com/sul-dlss/happy-heron/blob/f51a52c3e22990b77f7f9d3edfe04809b2c05d8f/app/components/dashboard/all_collections_component.html.erb#L28) too so I have adjusted it there too.

**Comment by amyehodge** [comment]
This appears to be fixed. Ready for release!
