### ISSUE TITLE
Remediate items where only the start date of a range was migrated to H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2224]
For a subset of items with date ranges, only the start of the date ranges was migrated to H2. We need to identify all of these items, collect the date range information from the MODS, and update the H2 database with the correct information. 

From Andrew:
I’ve finished putting together a list of druids where the date range should have been migrated into H2. 
https://docs.google.com/spreadsheets/d/12tTAUzsjjW8dhCcKhSv8vG_x43Bkpso-nK301AbEdLk/edit#gid=0
 
The Google sheet includes the druid and the range start and end dates, including the full MODS <dateCreated> tags. Arcadia, please let me know if there’s any other metadata needed to express a date range besides those two tags.
 
There were three categories of items:
 
1. Items where the range needs to be ported into H2 and also restored to the MODS in SDR because it’s already been republished without a range from H2
2. Items where the range needs to be ported into H2 but where the current SDR item and Purl is still ok (as of yesterday)
3. One collection record. It looks like we took out dates for collections created in H2 so I’m not sure if anything needs to be done with this object.
 
I haven’t checked all of the druids on the list in H2 but I spot-checked about 10 and they’re consistently missing the range end date. Since this is nearly 300 druids overall, I think we should ask for infrastructure support to copy in the date ranges to H2. It would be possible to edit each one to update the date but that seems like something we should try to avoid.

**Comment by jcoyne** [comment]
@andrewjbtw are you working on this ticket?  Do you need the developers to do anything?

**Comment by andrewjbtw** [comment]
I'm working on figuring out which druids need to be modified and then most likely that will lead to a dev task. I'd done a preliminary analysis right before we migrated off of Fedora but ran out of time to take that further, and now I need to re-do the analysis because items may have changed in the past few months.

**Comment by andrewjbtw** [comment]
I've completed my re-analysis of items with date ranges. There are two categories of druids that need updates:

1. Update the H2 work with the range that is still present in the Cocina

These items have not been updated via H2 since the migration away from Hydrus. So they only need to be updated in H2 because the record in Cocina/SDR has not changed since the migration.

There are 259 items in this category. CSV listing these druids with links to their Argo pages: [update-h2-date-range.csv](https://github.com/sul-dlss/happy-heron/files/9538404/update-h2-date-range.csv)

2. Update the H2 work with the range that used to be present in the Cocina/Fedora/Purl, then re-deposit via H2 to bring the records into sync.

This category is for items that:

- had a date range before the Hydrus --> H2 migration
- lost the end date of the range when migrated to H2
- were updated with a new version made via H2
- lost the range in SDR after the H2 version was made

There are 19 druids in this category. CSV including argo links, druids, and the date range start and end points as previously expressed in XML: 
[update-h2-date-range-and-deposit.csv](https://github.com/sul-dlss/happy-heron/files/9538410/update-h2-date-range-and-deposit.csv)

Since users have updated these items post-H2 migration, it might be worth getting in touch to see if the ranges are still correct.

**Comment by amyehodge** [comment]
I'm wondering if we will run into trouble in cases where people chose the "approximate" option with a specific date, since that is now not allowed. 3/20 of the druids in the list @andrewjbtw provided where the items have been updated since migration have this issue. 

Also, I'm deciding what to do with these items, but 15/20 are SUL staff and only 2 of the remaining 5 are people still at Stanford.

**Comment by amyehodge** [comment]
@andrewjbtw @jcoyne I am working my way through confirming the dates for the 20 in the spreadsheet. A couple people are out of town, but I hope to know about these all by the end of the week.

**Comment by jcoyne** [comment]
@amyehodge I think that makes sense, but I believe you previously said you didn't want email to be on for these deposits. Is that still the case?

**Comment by amyehodge** [comment]
@jcoyne I'm contacting all these users, who are largely SUL folks, so the emails are okay for these 20.

**Comment by amyehodge** [comment]
It looks like the one collection referenced above is yw836rh9143, the SUL Concierge Project collection. The note in the spreadsheet indicates it has already been fixed.

**Comment by amyehodge** [comment]
The short list that needed to be updated by hand have all been corrected. See notes at https://docs.google.com/spreadsheets/d/1p37es49BKA6KcAjHhMUNtW2XM0LFyIuQzU0HIeiMaw0/edit#gid=0
