### ISSUE TITLE
Update validations for SUNet ID search on collection form

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2278]
This is for the initial full collections form and the collection settings form and applies to the fields used to add manager, depositors, and reviewers. 

We still have a lot of users entering strings that aren't one single SUNet ID into these boxes. Sometimes this information manages to get saved, but of course doesn't provide the user access.

In the screenshot below, I was able to type in people, which was not found in the search, but the box still highlighted in green and I was able to save the form. However, the entry itself was not saved and the user was not alerted that it was not saved.

<img width="756" alt="Screen Shot 2022-06-08 at 2 02 28 PM" src="https://user-images.githubusercontent.com/5558511/172685875-5669b60f-a575-4471-b207-d0b376c2ac96.png">

Each box should have one single SUNet ID in it, so we should add validations that make sure this is the case:

- string must be 3-8 characters in length
- string must start with a letter
- string must contain only letters and numbers

Even with this, we won't prevent the issue with "people" above, so the validation should also require that the user has clicked the "Add" button in the search results in order to be able to deposit (for the initial form) or save (for the collection settings form).

**Comment by jcoyne** [comment]
One possibility is to clear the entry if you focus out of the input. Only the "add" button will save it.

**Comment by jcoyne** [comment]
Currenlty the search seems to ignore anything after a period (e.g. "jcoyne85.123"), and the form allows you to add that person, even though `jcoyne85.123` is not valid.

**Comment by peetucket** [comment]
The instructions in the page say you can add more that one person per box, separated by a comma and a space.  That's not true, is it?

![Screen Shot 2022-08-17 at 3.22.37 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/97524523-8f48-42f5-a8c1-82eb42a07a82)

**Comment by peetucket** [comment]
I'm working this from a couple ways. 

1. Adding in some client side javascript code to ensure you need at least 3 characters and have no more than 8 to perform lookups. 
2. Also, it looks like special characters (like a period) are silently causing a rails routing error in the background, which is why they are being ignored.  We can just remove this on the client side via javascript, so the user can't even enter them.

Basically suppressing input via javascript into that textbox to just what we think a sunet should look like.

The second challenge is what to do if the user leaves that text box after entering a sunet that passed these rules but was still not found via lookup.  Currently it will save just fine, but silently not saving that non-found user (as Amy noted).  Justin suggested clearing the box when it loses focus, which is a good idea, though you can still just press return and save the page without shifting the focus and noticing the value went away.

**Comment by amyehodge** [comment]
> The instructions in the page say you can add more that one person per box, separated by a comma and a space. That's not true, is it?
> 
> ![Screen Shot 2022-08-17 at 3.22.37 PM.png](https://camo.githubusercontent.com/aa21587714083a01ffdf9e5731d66f935b3f7b60125cc3c3bfb9fa68ae2bcb2b/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3539623961333566623032323264356465343737613166622f39373532343532332d386634382d343266352d613863312d383265623432613037613832)

oh my gosh @peetucket . I can't believe we haven't noticed this. This should be updated to say:

"Select the appropriate option below to add a manager or depositor. Enter one participant SUNet ID per box and then click "Add" to save the entry."

Should I make that a new ticket? THANK YOU for spotting this.

**Comment by peetucket** [comment]
No need for a new ticket - I can update the text with this one. That may help with some of the data entry issues too.

**Comment by amyehodge** [comment]
Agreed, @peetucket . Thanks!
