### ISSUE TITLE
Prevent situation where valid SUNet ID is not found in SUNet ID search

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2279]
This is for the initial full collections form and the collection settings form and applies to the fields used to add manager, depositors, and reviewers.

Sometimes a valid SUNet ID does not return results in the search.
<img width="612" alt="Screen Shot 2022-06-08 at 2 07 38 PM" src="https://user-images.githubusercontent.com/5558511/172686742-5bcb0cc0-27a2-45ed-8142-81e4aaa8c6e0.png">

If the user continues to try, the search does always seem to eventually find the user so they can be added.

While I suspect this is the result of a connection issue with the LDAP server that we can't do anything about, it would be good to prevent this from happening or, if we can't do that, to provide some feedback to the user that there was an issue and they should try it again.

**Comment by astridu** [comment]
Yes, I think that works. I may be confused at first as to why it didn't find it, but like most people, I would probably try again, especially with that message.

**Comment by jcoyne** [comment]
One possibility is to clear the entry if you focus out of the input. Only the "add" button will save it.

**Comment by peetucket** [comment]
related to #2278 and will be done in the same PR

We don't think there are any known issues on our end - likely due to LDAP.  Updating the "no search results found" message to what is shown below:

![Screen Shot 2022-08-18 at 10.31.00 AM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/71e766c0-0b00-47e3-a288-4b2818fd1dd2)
