### ISSUE TITLE
Add new content subtypes "portfolio" and "capstone"

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2299]
Mappings by Arcadia in #2287 

These should be added alphabetically to the lists in the work subtypes modal and in the subtypes list in the item edit form. 
"Capstone" should appear in the short list for Text.
"Portfolio" should appear in the short list for Mixed Materials.

In addition, to remove an inconsistency, please add "Music" to the short list for Mixed Materials as well.

For the following work types, "Capstone" and "Portfolio" should appear in the "See more options" section
- Data
- Software/code
- Image
- Sound
- Video
- Music

**Comment by amyehodge** [comment]
@hannahfrost Is there any time you think these should appear in one of the short list of terms for a work type?

**Comment by hannahfrost** [comment]
Add "portfolio" to Mixed materials

Add "capstone"to Text

**Comment by arcadiafalcone** [comment]
@amyehodge @hannahfrost Should these appear in the Theses & dissertations SearchWorks facet as well?

**Comment by amyehodge** [comment]
@arcadiafalcone Interesting question. I'm really not sure. And it makes me wonder if every undergrad is going to have to do this, and many of them eventually end up in SDR, whether a new facet might be justified?

**Comment by hannahfrost** [comment]
@arcadiafalcone Good question indeed. As @amyehodge suggests, this raises other questions given that we expect many more of these to come in the future. For now, I propose they should not be included in the theses and dissertations facet because they are not theses or dissertations. We need another solution, but that will require broader (and longer) discussion.  For the time being, can they just go under "Book"? (cringe)

**Comment by arcadiafalcone** [comment]
@hannahfrost @amyehodge The SearchWorks resource type facet will depend on the main type the user selects - since capstones and portfolios can be many things, they don't add any additional specificity to the resource type.

I was thinking not of the Theses/Dissertations resource type facet, but of the special view one gets by clicking on Stanford student work in the Theses/Dissertations card on the SearchWorks home page. I just did some exploration and that aspect could definitely use some review - the results are inconsistent depending on whether you enter via the card and then limit to Stanford student work or click directly on the link to Stanford student work in the card itself, and there are quite a lot of undergraduate ePortfolios etc. (380+) in the SDR that we are even indexing as Stanford student work but which are excluded from the default facet view.

**Comment by peetucket** [comment]
Closed via #2495
