### ISSUE TITLE
Dependency updates not working

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#231]
I suspect the challenges include:

- [x] `main` (not `master`) branch
- [ ] Need to `srb rbi update`

**Comment by justinlittman** [comment]
Also, a `bundler update` then `srb update` results in:
```
Printing /var/folders/bf/rnlx84r97hgd53jpkvmnxx780000gq/T/d20201026-42272-5r7d8d/reflection.rbi's symbol table into /var/folders/bf/rnlx84r97hgd53jpkvmnxx780000gq/T/d20201026-42272-5r7d8d/reflection.json
Traceback (most recent call last):
	6: from /Users/jlittman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5994/bin/srb-rbi:237:in `<main>'
	5: from /Users/jlittman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5994/bin/srb-rbi:196:in `main'
	4: from /Users/jlittman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5994/bin/srb-rbi:121:in `init'
	3: from /Users/jlittman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5994/bin/srb-rbi:232:in `block in make_step'
	2: from /Users/jlittman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5994/lib/hidden-definition-finder.rb:38:in `main'
	1: from /Users/jlittman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5994/lib/hidden-definition-finder.rb:47:in `main'
/Users/jlittman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5994/lib/hidden-definition-finder.rb:151:in `write_constants': /var/folders/bf/rnlx84r97hgd53jpkvmnxx780000gq/T/d20201026-42272-5r7d8d/reflection.rbi had unexpected errors. Check this file for a clue: /var/folders/bf/rnlx84r97hgd53jpkvmnxx780000gq/T/d20201026-42272-5r7d8d/reflection.json.err (RuntimeError)
```

**Comment by mjgiarlo** [comment]
Currently waiting on https://github.com/sul-dlss/operations-tasks/issues/2368

**Comment by jcoyne** [comment]
sul-dlss/operations-tasks#2368 is complete

**Comment by mjgiarlo** [comment]
@jcoyne yep, I'm back on this and theme colors today.

**Comment by mjgiarlo** [comment]
I am backlogging this issue because I haven't been successful at automating RBI updates in CI.

The problems:

* When running `srb rbi update` in an application post-update hook, the command runs, produces changes, and is committed, but the updates made are ones that break the build because `sul-ci-prod` has a version of glibc that sorbet doesn't support. I don't think I want to propose bumping glibc on that box or upgrading the OS. So, instead...
* Creating a docker-compose service for generating the type checks doesn't work either. There are two failures modes that depend on whether you use the built-in glibc or the sorbet-recommended (newer) glibc:
  * With the newer glibc, the build runs and winds up deleting nearly all RBIs because of a slew of "Can't find gem for /path/to/ruby/file" and Googling yields little of value to remediate this. In effect, Sorbet cannot find any gems for reasons that elude me.
  * With the built-in glibc, the sorbet executable in libexec cannot be launched due to missing linked libraries.

**Comment by mjgiarlo** [comment]
@jcoyne @justinlittman FWIW, the dep update build ran last night and the CI checks did not fail due to lack of srb rbi update. Worth closing this issue because NBD?

**Comment by jcoyne** [comment]
Sure.
