### ISSUE TITLE
Update SDR items when collection name changes so that the correct name is displayed on PURL, in SearchWorks, in Argo record, and in Argo facets

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2354]
Note that this issue affects items accessioned into SDR by many (or all) paths, and not just H2 items. H2 appears to accurately reflect collection name information on items at all times, but updated collection name information is not being properly displayed in Argo, PURL, and SearchWorks in all cases.

From Andrew:

I started looking into the issue when I was looking over the H2 doc and it looks like there are two different causes for the names not being updated in Argo vs. in the public systems.
 
1. In Argo, I believe the issue is the indexing delay as you’ve already identified.
 
Eventually the items will get the right display name via rolling reindexing but it can take a while. I think the change to the facet approach* will fix the problem in terms of opening the facets, but I suspect that the display titles on search results lists and show pages will still need reindexing to update the collection name.
 
I think triggering a reindex of all collection members every time a collection druid is updated is the only sure way to update the displayed title everywhere. Collection druids aren’t updated that often, so I don’t think this would be an undue burden on the system, as long as we prevent a large collection reindex from overloading the system. But the rolling reindexing does seem faster than it was in Fedora, so the approach of improving the facet so that it’s always right may fix things just enough that a bit of lag in other parts of the display is acceptable.

[*In Argo, facet on the collection druid and load the name for the druid when it is displayed. This would then avoid the need to reindex all the members in order for them to show the correct name in Argo.]
 
2. The situation for purls is more complicated.
 
At the most basic level, updating the collection name on the Purl requires updating the public XML, which mean republishing the XML for each item in a collection after its collection’s name has been updated. There’s no way to avoid having to do this because the Purls are static and there’s no rolling process to pull in new data. So what we’d need to do every time a collection name is updated would be to republish (but not necessarily re-release) every item in the collection (except for Registered items and dark items since they have no Purl). This is generally safe to do for items that already have Purls except in the case of items that are “Opened” – these might be in the process of being edited and could contain metadata not ready to be published.
 
For items in SearchWorks that do not have catkeys, I believe a republish will also update the SW display automatically. For items that do have catkeys, republishing isn’t enough, the item will have to re-run the releaseWF in order to update the 856 field. I’m unsure what needs to be done when the collection has a catkey but the items do not. I think the collection has to be re-released but the items will be fine with a republish.
 
I think that covers all of the situations. There’s
 
1.       In Argo, reindex the items
2.       For Purl, republish the items
3.       For SW, re-run the releaseWF if a catkey is involved

**Comment by amyehodge** [comment]
@andrewjbtw Can you review this and make sure that it accurately reflects the work to be done here? Thanks.

**Comment by andrewjbtw** [comment]
This is accurate but there is one part that I'd call a rough edge: whether to republish/re-release items that are in an "Opened" state. That can potentially cause a problem because an "opened" item might have changes that, after a republish, cause problems on the Purl. I'm not sure how we would exclude Opened items from a republish, however.

**Comment by jcoyne** [comment]
@andrewjbtw is this complete now?

**Comment by andrewjbtw** [comment]
I've confirmed with a collection on stage (1450 items) that these two parts are done:

- all of the Argo-side work
- republishing purls to update the collection

I can't easily confirm SearchWorks changes on stage because it's unclear how well the test SearchWorks actually integrates with SDR on stage.

This part has not been done, to my knowledge:

-  For SW, re-run the releaseWF if a catkey is involved

But I would argue that it should not be included in this ticket because the presence of a catkey means it's not an H2 issue anyway. It also continues to be unclear to me what it takes to reliably update a collection title in SW when a catkey is present and I think we need better cross-team collaboration and timing before we should take that on. When we manually try to update collection titles in SW it almost inevitably leads to repeatedly trying different strategies until one works.
