### ISSUE TITLE
Year fields for publication date and creation date should not display "1000" when arrow buttons are clicked

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2357]
All four of the year fields in this section display "1000" when the user clicks on the up or down arrows. I believe this is the minimum value set for this field, and if I recall correctly, a minimum value is required by the field.

![Screen Shot 2022-07-08 at 4 25 28 PM](https://user-images.githubusercontent.com/5558511/178065418-6b4a0cae-937a-4198-9fa1-9b91b645fe0e.png)

Users have provided us with feedback that this is not helpful and means that they end up having to erase and type in a value, since using the arrows once it says "1000" is not efficient.

Today I identified a published item where "1000" was listed inappropriately as the publication date, likely because of this weird interaction.

Ideally these should display the current date and the user can use the arrows to move backward in time from here (or forward again). If that's not possible, a better solution is to have this box be empty and not display the minimum. If for some reason having the arrows is what makes this have to display the minimum, then we should remove them entirely and default to just an empty box that the user has to type into.

**Comment by amyehodge** [comment]
@astridu Do you have any further feedback on this issue? Thanks.

**Comment by astridu** [comment]
Agree with your proposal above.

**Comment by jcoyne** [comment]
@amyehodge this is how the integer selector in the web browser works. It always starts at the minimum value (which we've specified as 1000).  I think we put it at 1000 so that it didn't start at 1.  So I'm not sure there is anything to change here.

If we want to change this to a free text field, we will have to ensure that nothing other than numbers are entered and that it's no fewer than 4 digits.  This may affect the usability as we would be abandoning the natural way of communicating the constraints on this field.
