### ISSUE TITLE
Remediate H2 objects with no deposit date in descriptive metadata

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/happy-heron#2370]
After #2368 is resolved, retrospectively add deposit dates to H2 objects.

Possibly also add modification dates for subsequent versions? TBD.

We can fill in version publication dates with each version's updated timestamp.

Should we reversion everything that gets remediated? To confirm with Amy & Hannah.

**Comment by jcoyne** [comment]
@amyehodge question for you

**Comment by amyehodge** [comment]
- We do want to reversion content so that it gets preserved.
- We do NOT want H2 users to get email notifications that new versions of their items have been deposited.
- For items in a version_draft state, I *think* we can skip these because when they are completed and deposited, this date information should get updated, though someone should double-check that.
- If this generates a line in the history table for the item, we should make sure the message displayed is understandable to the user and not something opaque and cryptic

**Comment by amyehodge** [comment]
Also, what about items that have been submitted for approval or have returned to depositors? We don't want to version those, but want to make sure the dates get added.

**Comment by amyehodge** [comment]
After discussion at stand-up today, we are going to take the route of creating a mechanism for doing a metadata-only deposit via H2 that will allow us to send the updated dates through for preservation without having to send the files. 

@amyehodge @jcoyne and @arcadiafalcone will work on the requirements for which set of content needs to be updated.

**Comment by amyehodge** [comment]
Re: what content needs to be updated:

Anything deposited in H2 before the fix for this was put into place a couple/three weeks ago (do we have an exact date for that?) will need to be remediated EXCEPT FOR:

- items in version draft states
- items that have been previously deposited but are now waiting for review again or have been returned for review
- items that have gotten catkeys
- items that are large data deposits — I should be able to generate a list of these from the tickets we make for them

I’m not sure how to definitively identify the items with catkeys, although these are going to be in a few specific collections. We might be able to skip those few collections entirely?

**Comment by jcoyne** [comment]
We can use the Argo facets to identify "Metadata source: Symphony" which shows the items that have catkeys. These could be marked as "locked".

We should "Lock" any large data items.


Then we can filter out "locked" items from the set to process.

The range of dates was "Aug 9th, 2021 - until #2417 went into production"

**Comment by amyehodge** [comment]
@andrewjbtw @jcoyne The list of large data deposits I identified is also in that spreadsheet above in a different tab, but since it's short I'll paste it here (JIRA ticket for deposit, druid):

https://jirasul.stanford.edu/jira/browse/LEGACY-5777	ch545gn8760
https://jirasul.stanford.edu/jira/browse/LEGACY-5768	fb002mq9407
https://jirasul.stanford.edu/jira/browse/LEGACY-5717	gj863qr6417
https://jirasul.stanford.edu/jira/browse/LEGACY-5738	jd768nw9509
https://jirasul.stanford.edu/jira/browse/LEGACY-5768	jj716hx9049
https://jirasul.stanford.edu/jira/browse/LEGACY-5776	jv404dc0795
https://jirasul.stanford.edu/jira/browse/LEGACY-5808	pq381cg6077 
https://jirasul.stanford.edu/jira/browse/LEGACY-5774	qk058jq2233
https://jirasul.stanford.edu/jira/browse/LEGACY-5775	qq718my6646
https://jirasul.stanford.edu/jira/browse/LEGACY-5574	rc797bt9574
https://jirasul.stanford.edu/jira/browse/LEGACY-5768	sm043zf7254
https://jirasul.stanford.edu/jira/browse/LEGACY-5775	sr637qt9337
https://jirasul.stanford.edu/jira/browse/LEGACY-5593	wv398fc4383
https://jirasul.stanford.edu/jira/browse/LEGACY-5738	zm622tr7008

I have locked all of these items in H2.

**Comment by andrewjbtw** [comment]
For the items with catkeys, let's skip editing without locking for now. Those workflows are going to keep adding new items that won't be locked so it might be best to see where things go with our upcoming discussions of staff workflows first.

**Comment by amyehodge** [comment]
@andrewjbtw So, just to make sure I'm clear, we should not lock them and also not edit them, correct? For those, @jcoyne or whoever will need to pull the druids to avoid from the spreadsheet. For the large data items, excluding locked items takes care of those.

Is that right?

**Comment by amyehodge** [comment]
Also, @andrewjbtw good point re: upcoming discussions on staff workflows and the perpetual making of more of those items. We def need a discussion on that.

**Comment by andrewjbtw** [comment]
Yes, that's correct. For items with catkeys, do not lock them and also do not edit them.

**Comment by amyehodge** [comment]
@jcoyne I think this is ready for you? Please let me know if you need anything else.

**Comment by jcoyne** [comment]
We want to re-deposit all "Deposited" items that are not locked
 and have a WorkVersion updated_at in the range of "Aug 1st, 2021 - until #2417 went into production"
 also exclude items that have gotten catkeys (https://docs.google.com/spreadsheets/d/1Hpp29zeivIsiyXz5C3627fCCpo8GzK_2I6B8zLwsqaA/edit#gid=0)

We want these to be redeposited (with a new version, and re-accessioned), however we don't want emails to go out to the owners. This will ensure deposit dates are added to the purl record if they didn't explicitly supply one.

**Comment by jcoyne** [comment]
Moved to #2674
