### ISSUE TITLE
Move existing druid search to Admin dashboard

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#2382]
This search functionality should be moved from the dashboard page you see when you log in and added to the Admin dashboard page. They should no longer be on the main dashboard page.

![Screen Shot 2022-06-10 at 4 23 54 PM](https://user-images.githubusercontent.com/5558511/173144981-a50a5389-9886-44ad-adbb-bf9120936a45.png)

The druid search should be available from the drop-down menu at the top of the page and should find druids for both items and collections. When the druid is found, user should be taken directly to the item view page or the collection details page (note that this currently goes to the collection settings page but should be changed).

Mockup showing Druid search in drop-down list along with error message if druid is not found: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/467760849

![Screen Shot 2022-06-16 at 3 40 11 PM](https://user-images.githubusercontent.com/5558511/174151314-e1bc34c6-04ac-4e9e-abe5-7d1439bff520.png)

**Comment by lwrubel** [comment]
I did the part about moving the search box over to Admin as part of the work with the All Collections table in #2415.

**Comment by lwrubel** [comment]
The DRUID search seems very similar to a Users search but the form mockups are different. For consistency, should I instead follow the model for the Users search (since that is already complete)? This is what the search forms would look like if following the Users form:

![Screen Shot 2022-08-18 at 9 50 19 AM](https://user-images.githubusercontent.com/1619369/185411736-4e79de25-28db-47a1-b13a-8f91649f2c09.png)

![Screen Shot 2022-08-18 at 9 52 12 AM](https://user-images.githubusercontent.com/1619369/185411992-ba29fbc1-10f0-4d80-ba12-6c44bb893b94.png)

**Comment by amyehodge** [comment]
@lwrubel That makes sense to me.

I think we had kept this as is because it was fine that way and presumed to be easier to keep that way, but having them be consistent would be lovely. Thanks for asking.
