### ISSUE TITLE
Year field fix from #2357 should also work in Chrome

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2432]
Currently when you use Firefox and click the button, it defaults to the current year, in Chrome it defaults to 1000.

See #2357 

Alternative approach:
- get rid of arrows by getting rid of input field type being a number (just make a plan text input field)
- ensure we still have validation to prevent a user from entering anything other than a 4 digit number in the range of 1000 up to the current year

**Comment by peetucket** [comment]
We've made several attempts at adjusting the default HTML behavior as described in #2357 (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) and it has resulted in unintended test failures due to complexity in the javascript introduced.  It has used up quite a bit of time.  See the linked PR #3109 

At this point, we may want to consider alternatives 

Potential alternatives:
- explore HTML data selector: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date   though this is usually used for specifying a specific date, and we want users to be able to do things like only enter a year
- accepting the current non-ideal default behavior
- getting rid of the arrows completely and just using a normal HTML text box (and adding extra validation to ensure it is a numeric year)
- others?
