### ISSUE TITLE
Make manager emails send again

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2652]
The manager emails that were updated in #2296 are no longer sending.

**Comment by peetucket** [comment]
On at least some of the methods (and possibly all), it looks like the code that sends email deliberately excludes the depositor if it the same as the collection manager:
https://github.com/sul-dlss/happy-heron/blob/main/app/services/collection_observer.rb

In other words, if the collection manager themselves makes a deposit to that collection and then makes changes that would trigger an email, they won't get the email (since they are both the depositor and the manager).  If there was a second collection manager, they *would* get the email.  If there is only one manager and that matches the depositor, then no emails go out.

Can we confirm if this is the desired behavior and could possibly be what's happening.

**Comment by amyehodge** [comment]
@peetucket Ah, okay. Thanks for clarifying that. I'll have to find another tester to help me out with this, so might take a bit.

**Comment by peetucket** [comment]
Note: we may also have some issues when owner is not the same as depositor with some of the logic in https://github.com/sul-dlss/happy-heron/blob/main/app/services/collection_observer.rb (i.e. it may be excluding depositors instead of owners).  See #2654

**Comment by amyehodge** [comment]
@peetucket I got Cathy to help me test this and these are indeed working.

Should we leave this ticket open but change it to reflect the note you made above? Or maybe open a new ticket to look into that?

**Comment by peetucket** [comment]
Great!  I'd suggest leaving ticket as is for now and briefly discussing after standup.  I think it makes sense to switch to using the owner in the related spots of the code too -- to me, once you switch a work to a new owner, that's a signal that the original depositor should not be used for any more of emails anymore.

**Comment by peetucket** [comment]
Should be fixed by #2676
