### ISSUE TITLE
Unable to go to the dashboard on stage

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#268]
Stage has the latest code deployed, when you click "Start here" you will be redirected back and get a message:  "You are not authorized to perform the requested action".   I've added logging and determined that the application_controller never gets any value from `request.env['eduPersonEntitlement']`  This might be something that needs configuring in puppet.

Maybe we need to set `ShibUseHeaders On`?

**Comment by jmartin-sul** [comment]
not sure about this since i'm not super familiar with puppet, but i couldn't find any instances of `ShibUseHeaders` (and a couple variants) being used in a way that seemed like setting that flag (though i see a couple things that look like reading/passing a value?).

one thing i did notice in the argo and ETD puppet configs was `profile::webserver::vhost::shibboleth::host` set to e.g. `argo-stage.stanford.edu`, `etd.stanford.edu`, etc.  i didn't see a value provided for `profile::webserver::vhost::shibboleth::host` in  the H2 stage puppet config.  maybe relevant?  again, not sure, mostly guessing.

**Comment by jcoyne** [comment]
@jmartin-sul in H2, we are using passenger standalone (so we can use websockets) which is different from all other dlss projects

**Comment by jmartin-sul** [comment]
@jcoyne ah, yeah, that'd make sense
