### ISSUE TITLE
 Robots should be able to change a file for an object without requiring re-staging of all files

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#27]
A change would be any combination of add/remove/replace

smarter interaction with prescat and techmd-service

**Comment by mjgiarlo** [comment]
@jcoyne Do you think this ought to move to common-accessioning? Or otherwise put: what all codebases need to be touched to accommodate this change?

**Comment by jcoyne** [comment]
@mjgiarlo I believe it's mostly common-accessioning, but certainly would affect techmd-service at the very least.

**Comment by amyehodge** [comment]
@jcoyne @mjgiarlo @andrewjbtw I'm looking through older tickets still in this H2. This looks to me like a change that impacts more than H2, and I'm wondering what the impact of doing this would be, if there is additional work outside this ticket to be done after this, and whether this is something we should look at getting in the summer work cycle? I'm just not clear on how this might fit or the priority. Thanks.

**Comment by vivnwong** [comment]
Is this the change we also refer to as making an object version update without requiring total content files re-accessioning? Even if we don't do this in the H2 WC, we should still think/plan about the UI implications. I would like to have this ready and implement this in the nearby WC.

**Comment by andrewjbtw** [comment]
It's worth discussing whether to implement this incrementally with H2 as a first step. I think the H2 interface may support this functionality already - from a UI standpoint - as it presents users with a list of their files and they don't really know whether those files are staged locally on the H2 server or not. We have to stage the files locally because of how the system handles versioning, but no one else really needs to know that.

For the rest of SDR, I think we need to do some analysis on what this could look like. Argo is the only place where you can see what files are currently in an object (other than H2, obviously) but Argo is not currently used to add files to any object. None of the accessioning pathways show you what's current. So we'd need either special interface work in potentially multiple apps to support things like replacing a single file using that app, or we'd need Argo implementation work to support file management in Argo itself. Which would raise the question - for me, if not others - why people can't make the first version of a druid with Argo, which would then raise the question of why Preassembly is a separate app just for depositing.

For H2, I can think of two special considerations:

- Downloading a file from the H2 page would have to pull it from SDR preservation if the files aren't staged locally. That may or may not make a difference in terms of download reliability. I'm not sure how big of a difference it would make given the underlying infrastructure is SUL's either way.
- We may want to make a change to the UI to make it clearer which files in a deposit are new and not yet deposited and which aren't. I don't think we do this currently, and I'm not clear it matters from a user standpoint. It may help us understand where each file is (only on the H2 server or only in the SDR) when troubleshooting, though that could be left to admins to work out in context.
