### ISSUE TITLE
If "Other" worktype is selected the user must provide details.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#272]
https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/432638956

**Comment by amyehodge** [comment]
@jcoyne The deposit form also needs to display the free text box for this category. Text entered in the modal should display in this form box automatically, but be editable by the user. While the checkbox options for other work types are optional, this free text description is a required field.

**Comment by amyehodge** [comment]
Summary of slack conversation:

1. This is a single value for this field, not multiple values.
2. We will not have a minimum or maximum length for the field.
3. All characters and all cases will be accepted.
4. Basically, no validation other than an entry of some kind.


Background
This field is intended to comply with a DataCite requirement for when someone chooses other so that we can make DOIs in the future. That requirement states: “The format is open, but the preferred format is a single term of some detail so that a pair can be formed with the sub-property. Text formats can be free-text OR terms from the CASRAI Publications resource type list.”

Since this is the only place we are getting any info for these deposits for our resource types, I’d like to be lenient and restrict it later if that turns to be necessary. With all the other item type options we now have, this option should be rarely selected. We will periodically review what has been entered here to see if there are additional subtypes (or types) that we should add to the selections to further minimize use of this category.
