### ISSUE TITLE
Do not update DOI state to "Findable" when decommissioning an item from H2

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2750]
We recently decommissioned some items with DOIs using the new H2 decommissioning feature and discovered that the DOI state -- which had been manually switched from "Findable" to "Registered" in the DataCite UI once we had been asked by the content owner to remove the item -- had been returned to the "Findable" state during the decommissioning process. 

The request here is that when a user is done decommissioning an item in H2, the item's DOI state should be "Registered."

**Comment by andrewjbtw** [comment]
A question I have is whether the `update-doi` step in the accessionWF tells DataCite to always call a DOI "Findable". If that's the case, as long as that step is triggered when accessionWF runs - which has to happen as part of SDR-side decommissioning - it will undo any prior change of the DOI state to "Registered."

**Comment by jcoyne** [comment]
@andrewjbtw how do we know if an object is "decommissioned"?  Should we add a new property to the cocina that indicates this? If we had something like this, the update-doi step could set the datacite metadata to "Registered".

**Comment by andrewjbtw** [comment]
I had the same thought - we need a way to indicate a DOI is not active. A Cocina field is probably the most appropriate but wouldn't that then mean that the decommission function in H2 has to update the object?

**Comment by jcoyne** [comment]
@andrewjbtw yes, but I can't think of a better way.

**Comment by andrewjbtw** [comment]
Bringing this comment over from Slack. After further discussion, I do think there's a way we could identify decommissioned items: check the APO to see if it's the SDR Graveyard.

Since all decommissioned objects use the “SDR Graveyard APO”, we could do one of the following at the `update-doi` step for items that have a DOI:

1. we could skip it for an item that uses the Graveyard APO (and leave the DataCite status alone)
2. we could run the step and if the APO is the Graveyard APO, then the step would change the status to “Registered” via the DataCite API

The first option would mean that someone (Amy, Hannah, or myself) would need to manually change the status in DataCite. The second option would make the change automatically.
