### ISSUE TITLE
Users can edit files lists in new versions of objects indepedent of original file upload mechanism

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2852]
Currently users can only version objects where the files were uploaded via the browser.  We need them to be able to also version objects where the files were originally uploaded via globus or via the single ZIP file method.

Currently when users create a new version for objects with browser uploaded files, users can:

1. upload a brand new file (to add to the object)
2. upload a file to replace one that already exists (will be replaced in current object based on filename matching)
3. delete an existing file
3. not upload any files --- just change metadata

We need to have this same functionality for objects where content was uploaded via globus or via the new single ZIP file method.  

Currently, H2 has no knowledge of files uploaded via globus, but if we want the user to be able to create v2 of a globus object and add a single file, replace a file or just change metadata, we may need to store metadata about the files in H2 so we can apply the same logic.  See #2861 (which is blocking this issue)

Requested functionality:

1. When a user creates a new version of an object, they are allowed to select the file upload type again (browser, globus or zip).

_If they select globus:_

1. The process is the same as described in #2847, which is we would create a new globus endpoint for the work/version
2. Any files the user puts into this new folder will completely replace the files in the previous version of the object.  It is basically like starting over again.   As this is destructive, we will need some warning messaging next to the option (which will be shown for a >v1 object).

see https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005615

_If they select zip upload:_

1. The user will upload a ZIP file, which will be expanded and completely replace the contents of the previous version.  
2. This is what is described in #2843.  As this is destructive, we will need some warning messaging next to the option (which will be shown for a >v1 object).

see https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005614 

_If they select browser upload:_

1. We show the files from the previous version (even if uploaded via globus or ZIP).
2. If the user does not change any files, they can change metadata and that is all that is changed (no file changes).
4. If the user adds a new file by uploading it to the browser, the file is added to the object.
5. If the user clicks a trash icon next to an existing file, that file is removed.
6. The user can also replace a file or upload a file at any levels.
7. The user may not add a blank folder.
8. The user may delete an existing folder, which will delete all files contained within it.
9. The user can add a description to any file.
10. The user can hide any file.

see https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005613

Note this is view is shown for the file browser upload mechanism for >v1 objects, which is different than what is currently shown for v1 objects.  It offers similar functionality, except that it shows the hierarchy in the object and allows users to add/replace/edit files at any level instead of just the top level.  We could also consider replacing the current file list view for v1 objects to match this view for consistency, though that is not required.

**Comment by justinlittman** [comment]
How would a user delete a file?

**Comment by peetucket** [comment]
@andrewjbtw and @amyehodge : i wrote up a possible flow for versioning of globus objects, which includes the ability to do a metadata only without having to have new UI elements.  See what you think.  Justin Littman also raises a good question of how a user would delete an existing file (not possible in the flow I described).

**Comment by amyehodge** [comment]
@peetucket your note about needing to have the entire hierarchy for a single file replacement is a good point and one that I think may be challenging to explain to users. We'll need to include that when we think about the UI. This is also needed to get the file in the right place, since there could be multiple files with the same name in different folders. 

Just as an example, I could have this:
`data folder
      station 1
           weatherdata.csv
           bathymetry.blah
           transectmap.png
           imagery.jpg
     station 2
           weatherdata.csv
           bathymetry.blah
           transectmap.png
           imagery.jpg`

Re: if a user adds a new file, presumably they would need to also include the hierarchy if they want it three folders in somewhere, otherwise that file will be accessioned at the top level. Is that correct?

Re: deletions....can we provide them with a list of the files on Globus and the ability to indicate what should be deleted? That feels very clunky, but currently I don't have any other ideas.

**Comment by peetucket** [comment]
Yup, hierarchy will be hard, but I can't really see another way, unless we build a whole hierarchical file representation UI of the globus object in H2, complete with controls for replacing, deleting, adding, etc.  

Using the globus UI for this purpose seems like a natural first step, though if we want to allow adding/replacing without having to "re-stage" all of the original files, you'd need to rebuild the original hierarchy and put the new/replaced file in the right place, otherwise we won't know where it goes.

The other option is to just have the user re-stage everything in globus, but we already talked about that not being ideal either.

**Comment by justinlittman** [comment]
Why don't we ask users how they would expect this to work?

I feel like we're trying to re-invent the wheel when users already have mental models about how this is expected to work from experience with Google Drive, Drop Box, other data repositories.

**Comment by peetucket** [comment]
I'm adding the analysis tag and updating the description to make it clear we should think about the best course of action here before proceeding with an implemenatation.

**Comment by vivnwong** [comment]
This will need @astridu's input.

**Comment by peetucket** [comment]
I have reworded this ticket based on the conversation we had today.  I believe we need some input from @astridu for the case where v2 of a globus object is changed by the user selecting "browser upload" to add/replace files.

**Comment by astridu** [comment]
I have mocked up an option for handling this. https://invis.io/YQ132HXFX2GR#/470471732_H2_Display
@peetucket @amyehodge 
In a nutshell (mockup: https://invis.io/YQ132HXFX2GR#/470471732_H2_Display):
1. user sees their initial deposit
2. user wants to edit one of the folders, clicks the edit icon next to it and sees an overlay where they can upload a new folder
3. user then sees the new folder on the view page.

A few questions:
1. Do we need to ask them if the file/folder they are replacing is >10GB, or would we know? If they select "Senary dataset A" to replace, do we know it's over 10GB, in which case, we would send them to Globus?
2. Can the user delete any of the files/folders on the deposit page? Can they delete on the view page?
3. If the user chooses to replace a file or folder after they have deposited, I'm assuming the file/folder is replaced in the same place in the hierarchy, but the names of the folder/file gets replaced if it is different.
4. What happens if the user replaces a folder with a file? Is that ok, and would the action be that the old folder and its contents are erased, and the new file is inserted into the same place in the file hierarchy?
5. Do we allow the user to deposit the files right away (on the overlay)? Or do they have to hit save and then deposit?
6. Do we allow the user to move folders/files around once they've uploaded them?

**Comment by amyehodge** [comment]
> 2. Can the user delete any of the files/folders on the deposit page? Can they delete on the view page?

I would say that yes, they can delete any of the files/folders. Having them be able to do this from the view page seems a significant shift from the current process, though it does seem more straightforward not have to go back into the full form. I do wonder if that's a bit confusing? Will it be clear to them which pencils bring up the whole form vs. just the file edit dialog?

And, actually, what is mocked up here on the view page seems to only support replacement and not deletion or addition without replacing.

> 3. If the user chooses to replace a file or folder after they have deposited, I'm assuming the file/folder is replaced in the same place in the hierarchy, but the names of the folder/file gets replaced if it is different.

The way this is mocked up, a user could choose to replace a specific folder but then replace it with completely different files with no relation to what was replaced. Is that okay? Seems like that should be fine, but we shouldn't being doing anything that assumes in that case that this is a new version of that folder.

> 4. What happens if the user replaces a folder with a file? Is that ok, and would the action be that the old folder and its contents are erased, and the new file is inserted into the same place in the file hierarchy?

Based on what I said above, I think that should be allowed unless we are trying to force this action to represent a more strict versioning of content files. And it would happen exactly as you've described it.

> 5. Do we allow the user to deposit the files right away (on the overlay)? Or do they have to hit save and then deposit?

Good question and I think goes back to the earlier point about doing this from the view page at all. If we are okay with diverging from "everything happens in the full form" then I think it's okay to deposit from here. That's much easier for the user.

> 6. Do we allow the user to move folders/files around once they've uploaded them?

I think this feature is out of scope for the current implementation. If a user wants to move things around, they'll need to do that outside of H2 and then reupload.

**Comment by peetucket** [comment]
To follow the model we have for all other editing, I think we want to ensure all editing happens only on the edit page (and not the view page), and that changes need to be saved/deposited to stick.  The pencil icons on the view page take you to the edit page, where you do the actual editing (they are just shortcut links to take you to the appropriate spot on the edit page).

**Comment by peetucket** [comment]
Closed in favor of simplified description in #2893
