### ISSUE TITLE
Add a page/Google doc with instructions for users on how to sign up for Globus and link to it

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#2855]
Users who have never used globus before but want to select that as an upload option need to have logged in at least once so they will be known to the API.  We need to provide them with some instructions that can be linked to from the work edit page if they select that option.

Ask @amyehodge for some verbiage for this page.

**Comment by amyehodge** [comment]
Note to self: nice set of instructions for the Duke Repository at https://research.repository.duke.edu/help#globus

**Comment by peetucket** [comment]
Thanks Amy.  May we should create a bit.ly link for that to actually embed in emails so we can update the location without changing the URLs in emails if we need to in the future?

**Comment by amyehodge** [comment]
@peetucket  don't think bit.ly will serve this purpose. I chose made a bit.ly link for this, but you now appear to have to pay for the service in order to change where the bit.ly link is pointing. So, if this gets moved, the bit.ly link will be dead as well. 

I can't get a short URL from Stanford because it's not at a Stanford subdomain.

**Comment by peetucket** [comment]
ok, no problems -- I'll just use that URL
