### ISSUE TITLE
Files should be checked for a change to hide/unhide file setting when sending updates

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2879]
Currently, in depositing a new work version, h2 checks whether files are previously preserved, based on filename. It uses the existing structural cocina if there's a filename match. It does not look to see if the hide/unhide file option in h2 work version has changed and no longer matches the existing cocina. The cocina generator should do this. 

The end result here is that the user checks/unchecks the box and the item is saved, but no change is actually made and the user is not informed that the change was not made.

Note that this issue is not currently affecting any user that we are aware of, but was raised in a work cycle discussion.

**Comment by andrewjbtw** [comment]
I am not sure how this looks in H2's internal settings, but the hide/unhide actions correspond to the Cocina publish/shelve settings.

Hide --> publish=no, shelve=no
Unhide (the default) --> publish=yes,shelve=yes

Note that in both of those cases, preserve=yes.

I think as long as a file was previously preserved, the system will publish and shelve it when "publish=no,shelve=no" is flipped to "publish=yes,shelve=yes". This is what happens when those settings are changed via Argo (though it's the accessionWF that actually does the publishing and shelving).

**Comment by mjgiarlo** [comment]
@amyehodge @andrewjbtw Is this for the current work cycle, or the first responder, or neither? Thanks! (Doing board grooming.)

**Comment by andrewjbtw** [comment]
My understanding from Slack was that the fix for https://github.com/sul-dlss/happy-heron/issues/2878 should also address this. The more general case would be phrased as:

> H2 should update Cocina structural when any property that maps to Cocina structural changes, even if the file itself isn't changed. 

I would consider that an FR ticket as a regression that came from a previous WC. But it's relevant to the current workcycle in that it will affect the behavior of versioning the hierarchical file layouts as well.
