### ISSUE TITLE
[happy-heron/prod] NotImplementedError: NotImplementedError

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/happy-heron#2924]
This is being triggered by a crawler. Can this be handled in a more elegant way (i.e., other than throwing an error)?

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/77112/faults/89706612)

**Comment by justinlittman** [comment]
This is being caused by a call to https://sdr.stanford.edu/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkZmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12cb475ef34f32cac3ee533546fc35cd468e8925/seda2022_documentation_beta.pdf?disposition=attachment

This call is not passing through Shib, so working with Ops to get it covered.

**Comment by justinlittman** [comment]
So H2 is special in that nothing is blocked by Shib, so that isn't a good option.

Considered rescuing the error and returning Bad Request. However, this is thrown from an ActiveStorage controller, which has its own controller hierarchy. It is possible to create a new controller that inherits from the ActiveStorage controller, but that additional complexity isn't warranted for this problem.

Instead, I'm going to settle for adding a comment to the HB alert.

**Comment by edsu** [comment]
@amyehodge It [appears](https://app.honeybadger.io/projects/77112/faults/93006826) that actual users are following links from https://edopportunity.org/ and getting this error?

- https://edopportunity.org/methods/ (follow the `SEDA Technical Documentation` link)
- https://edopportunity.org/research/ (click on the `Technical/Methodological` tab, and then click the `SEDA 2022 Special Release Technical Documentation` link).

If we aren't going to fix this maybe we should let the publisher know that they should update these links, since it is a site affiliated with Stanford?

**Comment by amyehodge** [comment]
Ah! These are not the links that had been corrected. I didn't know these were there and the webmaster has repeatedly missed fixing these. Thanks so much for finding these @edsu. I've contacted her again.

**Comment by amyehodge** [comment]
Update: the woman from SEDA has responded and indicated that they will update the two that @edsu found and check all the others, so, hopefully we won't be seeing this particular error again. 🤞
