### ISSUE TITLE
Prevent user from depositing without uploading any files to Globus

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2942]
This applies to when the Globus option is checked. Currently the user can check the box to say they have uploaded files and then deposit, even if there aren't any files.

The inclusion of a file has always been a requirement for self-deposit, and file upload is currently required when uploading files directly to H2. 

The only exception to this is the current implementation of Globus in production where they check a box to say they are using Globus and then admins are alerted to that and follow up with them to accession the files manually.

**Comment by andrewjbtw** [comment]
I will note that shortly after we implemented the current method - where a user can check a box to say they will use Globus - a user checked that box erroneously and submitted a deposit with no files, and turned out not to be using Globus at all. But because admins got an alert we were able to address that problem quickly.

**Comment by mjgiarlo** [comment]
@amyehodge I have option 2 working now. Being able to submit and then seeing a red box complaining at you for lack of files in the endpoint is a fairly straightforward implementation, arguably more so than layering more behaviors on the button (client-side work). OK for me to proceed with that option?

**Comment by amyehodge** [comment]
@mjgiarlo yes, thanks!
