### ISSUE TITLE
Uploading via globus the same filename to two different works causes error

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/happy-heron#2966]
Error below occurred when uploading a file via globus to one work when the same file had previously been uploaded to a different work. 

[happy-heron/qa] ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_active_storage_blobs_on_key"DETAIL:  Key (key)=(/1/unique-name.png) already exists.

## Backtrace

    line 34 of [PROJECT_ROOT]/app/jobs/fetch_globus_job.rb: block in new_attached_file
    line 33 of [PROJECT_ROOT]/app/jobs/fetch_globus_job.rb: new_attached_file
    line 16 of [PROJECT_ROOT]/app/jobs/fetch_globus_job.rb: block in perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/77112/faults/92430308)

**Comment by peetucket** [comment]
Following the code path:

1. The key that appears to be violating the constraint is created here: https://github.com/sul-dlss/happy-heron/blob/main/app/jobs/fetch_globus_job.rb#L32-L42
2. The method that asks the key to be created is here: https://github.com/sul-dlss/happy-heron/blob/main/app/models/attached_file.rb#L33-L37
3. The method that actually creates the key is here: https://github.com/sul-dlss/happy-heron/blob/main/app/services/active_storage/service/globus_service.rb#L22-L24

This looks like it should be globally unique since it combines the druid, the version number and the full filename (with path).  However, if you look at the HB error, I don't see a druid in the key detail... so I wonder if this is happening because a druid doesn't exist yet (work is in v1 draft and hasn't been submitted yet).

Perhaps using a work ID instead of a druid makes more sense when encoding the key?  

Not sure if this impacts previously uploaded items from globus.

**Comment by lwrubel** [comment]
Thanks, @peetucket. That looks like what's happening, indeed. The attached files are associated with a work_version, so I'm wondering if it makes any more sense to use that as part of the key?

**Comment by lwrubel** [comment]
Note: now getting this HB error (also seen earlier)

`StateMachines::InvalidTransition: Cannot transition state via :fetch_globus_complete from :first_draft (Reason(s): State cannot transition via "fetch globus complete")`

: https://app.honeybadger.io/projects/77112/faults/92680919

**Comment by peetucket** [comment]
Did someone reset the work_version state back to `first_draft` ?  It probably was `fetch_globus_first_draft` when it got stuck part way, since that it was the event transition that triggered this HB alert expects it to be.

**Comment by peetucket** [comment]
Or the state machine definition is not correct in some way if it also happens without the previous HB alert/key violation.

**Comment by lwrubel** [comment]
Looks like those HB errors were from retries of previously failed jobs. Tested on QA and those errors were no longer raised.
