### ISSUE TITLE
 Faraday::TimeoutError in DepositJob#perform 

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/happy-heron#2995]
See https://app.honeybadger.io/projects/77112/faults/93048685. 

Timeout is happening with a Globus deposit. Work is [6215](https://sdr.stanford.edu/works/6215), work_version 7951. It has 184 files. [Increasing the read_timeout](https://github.com/sul-dlss/happy-heron/pull/2993) on the SdrClient update call did not fix the issue.

**Comment by lwrubel** [comment]
The work version was eventually accessioned successfully. The remaining work is to investigate why sdr-api's work takes longer than the timeout. We raised the read_timeout to 30 mins, but @andrewjbtw reports that sdr-api took 80 mins to complete its work before it could respond back to H2.

**Comment by edsu** [comment]
[Another large deposit](https://argo.stanford.edu/view/cg185zq8485) seems to be triggering similar timeout errors: `
Faraday::TimeoutError: Net::ReadTimeout with #<TCPSocket:(closed)>
` 

https://app.honeybadger.io/projects/77112/faults/93048685

**Comment by edsu** [comment]
Just noting that when this happened previously @lwrubel had to manually remove the job from getting retried via h2's sidekiq dashboard.

**Comment by edsu** [comment]
The `GET` to `/v1/resources/druid:cg185zq8485` is pretty quick, based on experimenting with the sdr-client -- so I'm going to look at what is going on during the `PUT`.

**Comment by edsu** [comment]
I see that the PUT request to update a resource is calling [ResourceController.update](https://github.com/sul-dlss/sdr-api/blob/main/app/controllers/resources_controller.rb#L56-L77) which, before it creates a background job, calls `update_cocina_model` which (if you follow the call stack) results in [md5 and sha1 checksums] being generated for all the files. Since there was a lot of data this understandable takes a while.

Do we need to generate checksums here?

**Comment by edsu** [comment]
This should be resolved with the asynchronous generation of digests added in https://github.com/sul-dlss/sdr-api/pull/556
