### ISSUE TITLE
Create user folder for Globus workflow on initial save, whether user has logged into Globus before or not

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3021]
For those who have not logged into a Stanford Globus account before, making this change will eliminate the need for that user to save the item, log into Globus, then return to H2 and notify us that they have completed that step. So, the user journey for this feature would be the same for all users.

We recently learned from the people at Globus (U. Chicago) that it is possible via the API to create the shared folder and later have the correct permissions assigned automatically once the user has logged into Globus. These are the details they provided to us on how to do this:

— Permissions can be set for a user who has not logged into Globus before
— The API call to get the identity UUID, Auth get_identities call is used. The provision=True option ensures that identity is created, as unclaimed. Globus SDK documentation: https://globus-sdk-python.readthedocs.io/en/stable/services/auth.html#globus_sdk.AuthClient.get_identities 

See also #3021, #3022 and #3049.
See designs at https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/472346509_Globus_Auto_Account.

**Comment by lwrubel** [comment]
Now that we understand that there is UUID autoprovisioned for any @stanford.edu username looked up via the identities API, whether or not that person has used Globus before, we are streamlining the process as @akkornel suggested. We'll create the folder in the guest collection and assign the appropriate permissions to that UUID, regardless of user status.

Question for @akkornel about the suggestion above to send all users through an OAuth flow. Our app does not currently send users through a Globus OAuth flow, since we simply setting up a directory within a guest collection and giving them permissions to access it. Users are required to log into our web application using their Stanford account, so we already have their stanford.edu email (and they've previously created their Globus account and gone through the T&C process there). I can see how we can help new users by directing them to https://app.globus.com to go through the login process there. But what is the purpose for sending existing users through OAuth and reviewing the identity_set_detail​ info?

**Comment by akkornel** [comment]
Hi @lwrubel, this ticket certainly had me thinking for a while!  Now I understand your flow a bit better, and I think you'll be fine, but you might want to do a sanity check to see if users are also logging into Globus via means you might not expect.

A Stanford user might appear in Globus with any one of three usernames:

• If the Stanford user logs in to Globus through Stanford Login, they'll appear with the Globus Identity username `sunetid@stanford.edu`.

• If the Stanford user logs in to Globus by clicking on the "Sign In with Google" button, they'll appear with the Globus identity username `sunetid@stanford.edu@accounts.google.com`.  This will fail with folks who have a Base SUNetID, as Base SUNetIDs do not allow Google login.

• If the Stanford user logs in to Globus by clicking on the "Sign in with ORCID iD" button, they'll appear with the Globus Identity username `ORCID@orcid.org`.  What's more, they'll appear this way even if, when prompted by ORCID to log in, they log in via Stanford Login.

When a user hits the Globus Login page for the first time, the "Sign In with Google" and "Sign in with ORCID iD" buttons are pretty eye-catching, so there's a chance that a user will do their first log in via that path, and get a Globus Identity username that they don't expect.

So, even after you've told the user to log in to Globus for the first time, you might want to do a check to see if they ended up logging in to Globus using Stanford Login.  You can do this by calling the "Get Identity" API, but setting `provision=False`.  If you see that the `sunetid@stanford.edu` identity doesn't exist, and you know the user has logged in to Globus before, then you know they logged in through some other identity provider (either Google, ORCID, or another institution).  In that case, you might want to prompt them to log back in to Globus, and then [link their Globus Identities](https://globus.stanford.edu/accounts/link.html).

> But what is the purpose for sending existing users through OAuth and reviewing the identity_set_detail​ info?

Sending users through a Globus OAuth, and reviewing the resulting `identity_set_detail`, would let you know for sure that they have a Globus Identity set up for their `sunetid@stanford.edu` Globus Identity username.  I was thinking "Well, if you need to get the user to log in to Globus anyway, you could send them through an OAuth."  It would give you confirmation that the user made it through the first-time Globus Login, it would confirm how they logged in, and it would let you know if they have any linked Identities (just in case that info might be useful).

I hope this information helps!  Let me know if there's anything I can do to clarify, or provide additional information.

**Comment by lwrubel** [comment]
Belated thanks for this information, @akkornel. I had to spend some time thinking about it too. :) 

We try our best to steer people to log in with their Stanford credentials, but I see how it's tempting to click those other options. We don't always know if the person is a previous Globus user with non-Stanford credentials. I didn't know about the `provision=False` option so that's helpful to know how to check a username first, without triggering autoprovisioning. 

In the current setup, we look up user by stanford.edu username and set up a share for them with access given to that identity. The problem you're pointing out would arise when the user clicks on the link to the share we set up and then creates an account incorrectly via Google/ORCID and gets a permission denied message. 

The [link their Globus Identities](https://globus.stanford.edu/accounts/link.html) instructions you provided would be helpful info to include in the instructions, @amyehodge if not already there. That would be one way to resolve the issue if a user went down the wrong set-up route and then had to set up their stanford.edu account and link it to the other one, in order to get access.
 
As we get more experience with how people are using Globus for deposit, this info is all helpful for determining how we might add in a check. Thanks for walking through this!
