### ISSUE TITLE
Deposit error for work 6702: globus transition problem.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3080]
See https://app.honeybadger.io/projects/77112/faults/96031287

We just had an honors thesis trigger this HB error that looks serious: https://app.honeybadger.io/projects/77112/faults/96031287. I see 5 files in H2 and only 4 on Globus, so I wonder if that’s causing a problem? These submissions are usually under a time constraint, though I haven’t checked in with the collection manager to find out details about that yet.

**Comment by andrewjbtw** [comment]
I wonder if the depositor added the thesis file via the web app after uploading the WAV files via Globus.

**Comment by amyehodge** [comment]
Okay, based on that @andrewjbtw I will contact the collection manager and ask her to let us know if she encounters any issues when approving that. And possibly to let us know when she does so we can keep an eye on it. 

Does that plan suit everyone. @edsu ?

**Comment by peetucket** [comment]
That sounds like a good explanation and a reasonable response.  Basically, since the "fetch globus job" is a background job that can take some time, if you change the state of the object in the middle of that job (by uploading another fike), I think it gets confused.  I'll create a ticket for this as we should figure out how to deal with it more gracefully (by either disallowing editing while globus fetch job is still not done) or maybe just allowing that transition to occur if it's actually ok.

**Comment by edsu** [comment]
Yep, that sounds good @amyehodge -- thank you all for helping the FR with this, super appreciated!

**Comment by amyehodge** [comment]
@edsu @peetucket @andrewjbtw This item has successfully completed accessioning and looks good in Argo.

I'll note that the amount of content on this PURL is under 1GB and could have been submitted more easily via the zip file upload. I may contact this person to see why they didn't choose that. Maybe we need to make the instructions clearer.
