### ISSUE TITLE
Affiliation field should allow type-ahead search against RoR

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3100]
#3156 (and mapping in #3099) adds an affiliation field to the contributor section of the form, and really should be completed first, but this ticket can be worked on in parallel or before mappings are ready.  

Background:
- RoR is a registry of known institutions, see https://ror.org/   It has an API or a downloadable database option.  It provides unique URIs for institutions.  See https://ror.org/registry/#about-registry-data
- Having identifiers is better than strings
- We would like to have the affiliation field provide type ahead support, searching the RoR registry and recording the URIs if found.

Tasks:
- Investigate/consider caching vs real-time API lookups against RoR (see comments below for background info to inform decision)
- once decision is made, work on the backend for autocomplete. use existing keywords autocomplete as a model for this autocomplete (uses stimulus autocomplete with an H2 endpoint that proxies the call to the remote third party API)

See https://projects.invisionapp.com/share/NP138M0QX7T3#/screens/473166568 for design and https://docs.google.com/presentation/d/1FI9yn7vUSeX7Yd5IemrLxnYH2__JlTxNwgP8guATb18/edit#slide=id.g2419bf83bea_0_0 for requirements

**Comment by amyehodge** [comment]
In a discussion with Rochelle and Zach Chandler, we agreed that if we used a local copy that updating it annually would likely be adequate, even though the organization updates it approximately twice a month (at least lately). 

In case you're interested, here are the most recent ROR registry release notes: https://github.com/ror-community/ror-updates/releases/tag/v1.26. All added or modified organizations are listed if you want the details.

Total organizations: 105,354
Records added: 60
Records updated: 374

**Comment by amyehodge** [comment]
From [2023-05-ROR-in-Repositories-Best-Practices-draft](https://docs.google.com/document/d/1N-LnHZ9vGb_e6XJmdGU5eAVgY2ZQQjYtlRA2BffHNqs/edit#heading=h.ip3vqe32gor), which is 

"Rather than making calls to the live ROR API, consider using a local copy of the ROR dataset or running a local instance of the ROR API in Docker.

The live ROR API always has the most current data and is generally reliable, but as publicly-available, community-shared open infrastructure traffic (and therefore response time) can vary. The ROR API's rate limit is a maximum of 2000 requests in a 5-minute period, and API traffic can be quite heavy at popular times, like midnight UTC."
