### ISSUE TITLE
Write rake task to output ORCID contributors with read-only ORCID access

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3104]
Note: depending on where the work in #3160 is done, this may end up in a different codebase than H2. Or it may require that we add the mais-client gem to H2?

For contributors with an ORCID that have also been through the MaIS authorize integration and have authorized write access to their ORCID profile, we will push works to ORCID via the ORCID API in #3103

See https://docs.google.com/document/d/1vAMI3OqJDxdQiLyseBi0IMtrL3HiL7y6cj0fT_P8t80/edit for full description and diagram

For the purposes of outreach and to encourage ORCID adoption and enabling write access, we would like to be able to 
- get a list of get a list of contributors that have ORCIDs
- check each ORCID against authorize portal (as determined via the MaIS API) to determine if read only access was selected

This can be a rake task run on demand by an engineer as needed.

Output is all sunet/orcid pairs that are contributors in H2 and have read only scope in MaIS:

`sunetid,orcidid`

See #3117 for example commands used to fetch list of ORCIDs for contributors and the usage of the MaIS API (currently only in sul-pub)

**Comment by amyehodge** [comment]
@peetucket It would also be great to include in the info that is saved 1) which work id or druid the ORCID came from and 2) which criteria above got them on this list -- not authorized at all or read-only access.

**Comment by peetucket** [comment]
Is this something you'd envision being an admin report run on demand?

**Comment by amyehodge** [comment]
@peetucket I'm thinking maybe we automate a monthly report. I'd probably rather it be retrievable from the H2 UI than sent via email, though the email option would allow us to send it to someone els who might be interested, like Rochelle, who doesn't have access to the H2 admin features.

If we did it on demand, it seems like that report would get longer and longer over time. In that case we'd want to have a way to limit the results that are returned but we would then have to know the last time we ran the report. Because we'll be managing somewhere outside the app who we have already emailed and actions that need to be taken etc.
