### ISSUE TITLE
Test large file size globus object in stage/qa

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3270]
1. Create a large globus object (~but less than 4 TB).
2. Create a new H2 work.
3. Select large globus object mount.
4. Deposit
5. See what happens

Success = object deposited and nothing exploded

**Comment by andrewjbtw** [comment]
Tested on stage with a nearly 4 TB object:

```
1001G   1000G-file.bin
2.0T    2000G-file.bin
1001G   copy-of-1000G-file.bin
4.0T    total
```
I went through the normal Globus deposit workflow:

- Filled out form with Globus option checked
- Got Globus folder
- Transferred files via Globus interface
- Returned to H2, checked box to confirm files had been copied, saved form
- No problem with file list showing up on item page
- Clicked deposit
- Deposit job ran for about 36 hours
  - druid was assigned and registration ran successfully
  - files copied successfully into accessioning workspace (/dor/workspace)
- accessionWF started, moved on to `technical-metadata` step with no problem

At this point, all the remaining work to reach accessioning would be in the "common" part of common-accessioning: the accessionWF and preservationIngestWF. Since we have a large object (5 TB) in prod running through common-accessioning right now, we decided to end the stage test here. Running it through to preservation and replication would create a large amount of data that would be difficult to delete until we can reset the whole stage environment.

In case we change our minds, I'm leaving the data in the accessioning pipeline but moving it to a different folder so that the accessionWF will stop with an error when it can't find the files in the expected location. If we want to finish the whole process end-to-end, we can move the files back.

The test druid is:

- H2 link: https://sul-h2-stage.stanford.edu/works/19309
- Argo link: https://argo-stage.stanford.edu/view/druid:qy991zf4953
- Folder path in accessioning pipeline: `/dor/workspace/qy/991/zf/4953/qy991zf4953`

**Comment by peetucket** [comment]
Calling this a success.  Thanks Andrew
