### ISSUE TITLE
Auto-generated citation option should be on unless user turns it off

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3277]
The auto-generated citation is on when initially creating an item, but if you save the item as draft or deposit it, the next time you open it the auto-generated citation option is off. It should stay on unless the user turns it off.

Steps to recreate:
1. Create new draft item. Fill in form fields. Note that auto citation is on and is being properly generated.
2. Save as draft.
3. Click pencil icon to update.
4. Note that the auto generated citation is off and that changes to the form fields that are part of the citation are not reflected in the citation.

Same for immediately depositing:
1. Create new draft item. Fill in form fields. Note that auto citation is on and is being properly generated.
2. Deposit item
3. Once deposit is done, click pencil icon to create new version.
4. Note that the auto generated citation is off and that changes to the form fields that are part of the citation are not reflected in the citation.
5. Make change to the title
5. Turn on auto citation
6. Deposit item again.
7. Title change is seen in citation for deposited item, i.e. auto citation being turned on updated this like it should, but 
8. click pencil icon to edit. Note that auto citation is back off again.

**Comment by aaron-collier** [comment]
@amyehodge I may have found a bug that is a symptom of this bug, a new bug, or just related - If I'm able to resolve it during this work I will, otherwise I'll open a follow up ticket.

What I'm seeing is that the generated citation doesn't change while editing the page the first time. So I initially entered 2023 as my publication year, which updated the citation, but then changed it to 2020 and it did not get updated on either the form or the record:

Editing:
![Screenshot 2023-07-19 at 1 18 49 PM](https://github.com/sul-dlss/happy-heron/assets/2294288/fb69735d-f8a7-42e3-82ad-678c583513eb)

Deposited:
![Screenshot 2023-07-19 at 1 20 00 PM](https://github.com/sul-dlss/happy-heron/assets/2294288/0448cd92-f409-4836-b4dc-811ff0fd4e99)

**Comment by amyehodge** [comment]
The rules around the use of the publication dates in the auto citation and complicated. Hannah and I have this on our list to review sometime, so if the only issue you're seeing is with the publication date, I wouldn't worry about it now.

Also, if your original publication date entry was 2023, it may have simply been adding the current year by default and ignoring the publication date. You just couldn't tell because they are the same.

**Comment by aaron-collier** [comment]
Ah - Ok, cool... this isn't the case with the title (i.e. I can change the title a few times and the generated citation updates...) so yeah, I think you're right 2023 is there automatically, so I think we do have an issue - but as you say, it's complicated :-)

**Comment by amyehodge** [comment]
@aaron-collier I think originally we intentionally weren't using the publication date, because it was confusing the original publication with the publication via SDR. But we have some use cases indicating that we need to revisit that decision.
