### ISSUE TITLE
Investigate why H2 sometimes does not get the deposit completed message

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#3297]
In #3296 and #3254, we have a couple items that have completed accessioning properly, but H2 did not get the message, and continues to show them as depositing.  The two items in those tickets were manually updated to complete the deposit, but it would be good to investigate why this might be happening.

How it should work:

1. H2 monitors the h2.deposit_complete queue: https://sul-rabbit-prod.stanford.edu/#/queues/workflow/h2.deposit_complete
2. This starts a `app/jobs/deposit_complete_job.rb` job.
3. This calls `app/services/deposit_completer.rb`

Not sure where the breakdown is.  Possibilities:

1. Message not being sent?
2. Message not on the queue?
3. Job not picking up the message from the queue? (though there is nothing in the queue now, so this seems unlikely)
4. Job or `DepositCompleter` class failing (though no HB alerts)

**Comment by aaron-collier** [comment]
I have not been able to identify a cause or timing related to this. There are instances of items showing deposits during the same timeframe and 1 doesn't complete the deposit while the other does..

**Comment by jmartin-sul** [comment]
another instance of this was discovered today: https://sdr.stanford.edu/works/7177 / https://argo.stanford.edu/view/gm130bx3201

i successfully used the instructions from the wiki to unstick it: https://github.com/sul-dlss/happy-heron/wiki/Complete-a-deposit-stuck-in-the-%22depositing-state%22

there have been at least one or two other occurrences of this problem in the weeks since this issue was originally filed.

per @vivnwong and @amyehodge, we should use this issue to track other occurrences of the problem, both to figure out the frequency at which it happens and to get druids and work IDs for use in further troubleshooting.

another thing we could do to help debug is to alert when there are deposits that are taking a long time to complete.  this is ticketed here: https://github.com/sul-dlss/happy-heron/issues/3371

**Comment by amyehodge** [comment]
This occurred for druid: tz479yh3220 on Oct 11 at 11am PT.

**Comment by justinlittman** [comment]
```
I, [2024-03-19T10:40:19.082596 #3785951]  INFO -- : Trying deposit complete on druid:vb371yk4055
I, [2024-03-19T10:40:20.506940 #3785951]  INFO -- : Not completing deposit for druid:vb371yk4055 since not found
I, [2024-03-19T10:40:21.065337 #3785951]  INFO -- : Assigning druid:vb371yk4055 to object-7557
I, [2024-03-19T10:40:23.493333 #3785951]  INFO -- : Retrieving metadata from: /v1/resources/druid:vb371yk4055
I, [2024-03-19T10:40:23.923096 #3785951]  INFO -- : Retrieving metadata from: /v1/resources/druid:vb371yk4055
I, [2024-03-19T11:00:04.236289 #4047594]  INFO -- : Object is still in depositing state, but accessioning is complete: druid:vb371yk4055
```

**Comment by peetucket** [comment]
are we keeping this open even after #3481 was merged just in case it happens again?

**Comment by justinlittman** [comment]
Optimistically closing, with the option to re-open later if necessary.
