### ISSUE TITLE
View a work

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#33]
Update the view page to look like this as much as possible:

https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930436

**Comment by justinlittman** [comment]
#397 is an initial cut at viewing a work. The following parts of the design were not implemented and may need to be ticketed separately. (cc @amyehodge).

1. 
![image](https://user-images.githubusercontent.com/588335/98597030-5885a080-22a6-11eb-907b-37a519018ed3.png)

2.
![image](https://user-images.githubusercontent.com/588335/98597256-bc0fce00-22a6-11eb-8410-d66da48e5451.png)

3. Link to collection not implemented since no collection detail page yet.

4. Not available:
![image](https://user-images.githubusercontent.com/588335/98597348-e2356e00-22a6-11eb-96fd-0cb71e2e6b3a.png)

5. 
![image](https://user-images.githubusercontent.com/588335/98597452-10b34900-22a7-11eb-9c79-94211c49efad.png)

**Comment by justinlittman** [comment]
6.
![image](https://user-images.githubusercontent.com/588335/98597566-37717f80-22a7-11eb-979b-af60cba398b0.png)

7.
![image](https://user-images.githubusercontent.com/588335/98597735-730c4980-22a7-11eb-9a3a-c4dfa6d126b6.png)

8.
![image](https://user-images.githubusercontent.com/588335/98597875-a5b64200-22a7-11eb-80fc-424655392ffb.png)

9.
![image](https://user-images.githubusercontent.com/588335/98598000-ced6d280-22a7-11eb-962a-1b1aad886c86.png)

10.
![image](https://user-images.githubusercontent.com/588335/98598064-e8781a00-22a7-11eb-8a54-55650a46144d.png)

**Comment by amyehodge** [comment]
@justinlittman This is looking really good.

A few comments:

1. This should actually be SUNet, but if we can along with that retrieve the name from LDAP that would be better. Something like "thalassa (Amanda Whitmire)". This is a real example where the person is hard to guess from the SUNet. We don't need the depositor email here.

Also, the contact info should be removed from this table as it is listed properly in the titles and contact section below. That was an inadvertent duplication.

I also want to move the subtype down to the Description section under keywords. The Details section then will have only things that are not editable by the user, which makes more sense as this section does not have a pencil icon.

5. We talked about this in planning on Monday and I want to clarify. NO FIELDS are required to save a draft. That means these notices of missing information do need to be implemented. The workflow is:

- new item created
- user saves draft and is able to leave all the fields blank if they want
- validation shows what is still needed
- once all validation passes, the "deposit" link at the bottom of the page is enabled
- user can then deposit the work

7. See #5. Drafts can be saved without all fields filled in, so we do need the progress bars on the item view pages see users can easily see what they still need to do.

It looks like we will need some further tickets for all of the pieces not implemented.
