### ISSUE TITLE
Alert admins when item has been depositing for more than 48 hrs.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3371]
For when there is time.....

Some items are completing accessioning, but H2 doesn't know about it so they remain "Depositing..." and are not editable.

Conversation from slack:
Andrew Berger
https://stanfordlib.slack.com/archives/C69UZCJ8M/p1693501538236339?thread_ts=1693402344.675239&cid=C69UZCJ8M
I wonder if it would be useful to have an alert that lists items that have been “depositing” for over a certain number of days. The big globus deposits so far have been 1-2 days, probably if something is depositing for more than 2 days it’s worth a look.
We have an alert like this based on workflow status but we can’t use that here because the workflows show all the steps complete, it’s just H2 doesn’t hear about it.

Mike Giarlo
https://stanfordlib.slack.com/archives/C69UZCJ8M/p1693502179780759?thread_ts=1693402344.675239&cid=C69UZCJ8M
That might be the sweet spot? We'd need to record when an item entered the depositing state, which isn't a huge change.

**Comment by jmartin-sul** [comment]
this is meant as a tool for helping to debug https://github.com/sul-dlss/happy-heron/issues/3297 (and to automatically find occurrences of it for remediation, since we currently only find them when people notice things stuck in the `Depositing` state)

**Comment by jmartin-sul** [comment]
#3391 adds an audit job that runs hourly.  it looks for any `depositing` work that's actually done accessioning, and automatically corrects the state in H2, as well as sending a honeybadger alert to let us know about the issue.

we might be able to close this ticket since #3297 is about investigation/tracking?  PR #3391 doesn't do exactly what this ticket asks for, but it might actually be slightly more useful, since it sends more timely alerts and auto-fixes the bad states it finds?

**Comment by amyehodge** [comment]
Agreed @jmartin-sul . I'm closing this ticket.
