### ISSUE TITLE
Request for report from H2 on upload_option

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#3474]
I'm interested in understanding how often the different upload options have been used -- browser, zip upload, and globus. I'd like to review some of the items for the different upload types, so I'd like the report to contain the work version and upload type for each H2 item.

@edsu  did this quick query, but @lwrubel has ascertained that when the zipfile and globus uploads are completed, they are changed to "browser," so this won't give me all the information.

```
h2=# select upload_type, count(*) from work_versions group by upload_type;
 upload_type | count
-------------+-------
 globus      |    27
             |    12
 browser     |  9655
 zipfile     |     4
```

The history tables do log when unzipping is started and completed, as well as when globus fetch is started and completed, so perhaps there's a way to use that information to get at this.

**Comment by edsu** [comment]
It does look like we will need to use the `events` table to do this since the `upload_type` gets [switched to `browser`](https://github.com/sul-dlss/happy-heron/blob/3a5a9639576907ba16440f2f0d73236f668e137b/app/jobs/unzip_job.rb#L31) once the ZIP file is successfully unzipped.

Here's the query I came up with to get all the `unzip_complete` events with when they happened and the user that initiated it:

```sql
SELECT events.created_at, works.druid, users.email
FROM events, users, works
WHERE eventable_type = 'Work'
    AND event_type = 'unzip_complete' 
    AND events.user_id = users.id
    AND events.eventable_id = works.id
ORDER BY created_at DESC;
```

I'll send the results directly to you since they have email addresses in them.
