### ISSUE TITLE
Add a cron job to look for ActiveStorage objects that are not attached to works

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#481]
...and delete them.

The use case here is that someone starts to create a draft, uploads some files and then walks away before they ever save the draft.  We need a way to ensure these files are cleaned up.

**Comment by amyehodge** [comment]
@jcoyne Is this something we need to include in the upcoming work cycle?

**Comment by jcoyne** [comment]
It is probably something we should do.

**Comment by justinlittman** [comment]
We don't we wait until storage fills up and it crashes. That's worked well in the past ...

**Comment by aaron-collier** [comment]
Picking up this ticket, I see how to correlate uploaded files to `AttachedFile` (and compare if an uploaded file ID is not in `AttachedFile`). I'm wonder what considerations should be made here:

1 - How often do we want to clean up files? Or, alternatively, how old of files (i.e. 7 days) do we want to remove?
2 - What should happen if we delete a file that isn't attached to a work because someone walked away form their browser for a while and comes back to it? I'm guessing this should be rare if we time when files are removed, but I assume it's a possibility.

**Comment by amyehodge** [comment]
@aaron-collier 
1. I would have said that we should give it a few days, so 7 sounds good to me. If you never once clicked 'save' and you come back a week later, I don't think you would expect your work to still be there. I definitely have this happen when we I go back to an tab the page reloads and everything is blank again. And it happens much faster than 7 days sometimes.
2. So, if a user opens the form, uploads a file (or more), adds some metadata, never clicks save, and leaves that window open but doesn't come back to it for 8 days (assuming we delete the files after 7 days), what happens? When they return to that open window and continue working, I would assume the info in the form fields would still be there, and when they 1) clicked the save button, they would ideally get a message that the files that were there had not been saved or 2) clicked the deposit button get the validation error that files are required.

**Comment by astridu** [comment]
Yes, this sounds good. 7 days is pretty generous.
