### ISSUE TITLE
Email notifications: "Depositor: Draft in progress, not submitted/published"

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/happy-heron#589]
https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.lj2h48ox03kd

Example implementation: https://github.com/sul-dlss/happy-heron/pull/673

**Comment by jmartin-sul** [comment]
closing this for now, but will note here the possible delta between the implementation that was merged last month and the spec...

from the PR description
> This PR as is has a bit of a delta from [the spec]: I'd originally interpreted as notify at two weeks, then every four weeks after that... but upon re-reading, I think the intent is notify at two weeks, again at four weeks, then every four weeks after that? If so, it should be easy enough to make that change in this PR or in a follow on (happy to do either). [_PR is now merged, so would need a follow-on now)_]

the comments on the spec doc linked from this issue say:
> @hannahfrost -- How much time has elapsed before the reminder is issued? How many reminders are sent before they cease? When a recipient's SUNet account becomes inactive before completing a deposit, can we detect this and cease sending the notifications?
>
> @amyehodge -- My inclination is to go with two weeks, then at a month, and monthly thereafter. I wouldn't stop as long as the SUNet is valid, but it would be nice if they had an option to request that they stop. That might be out of scope right now.

there is, indeed, no attempt at present to verify whether the SUNet is still valid.

if we want to adjust the interval between reminders, or validate that the SUNet is still valid, i'd be slightly inclined to open separate new issues for either/each of those things, rather than reopening this one (but i don't feel strongly about that).

**Comment by amyehodge** [comment]
@jmartin-sul I think that notification interval is fine.

It would be great to have verification if SUNet IDs are still valid, but perhaps we would want that for more than just this notification. Question: what happens if the email is sent and the SUNet isn't valid? Would that bounce back to somewhere, basically letting us know it isn't valid? That could be a way of getting this info indirectly.

**Comment by amyehodge** [comment]
I would have expected to have received a notification about [this work](https://sul-h2-stage.stanford.edu/works/13373) that has been in draft since April 20, 2021, but I haven't. Can someone check on this?

**Comment by amyehodge** [comment]
filed new ticket #1419
