### ISSUE TITLE
Make  Collection Description a text area

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#791]
wireframes: https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930437
design doc: https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.m80ipne8rlzk

**Comment by jcoyne** [comment]
@amyehodge Is this a requirement that you have or is this just because we see this it on the wireframe?  Is it possible that this was not a considered decision and is just part of the text attribute widget in the design palate? If we do want to proceed we need to know how many characters each field should be able to support and if we want to support line breaks. Should the drag widget be able to move the field vertically or horizontally or both?  Do we need to remember the dimensions this was dragged to when they come back to this page?

**Comment by amyehodge** [comment]
@astridu I would like your thoughts on Justin's questions above.

When pressed, I would rank this as a nice-to-have rather than a must-have. However, if we don't have it, then some fields should be default be larger so that more of the content is easily visible without lots of arrowing up or down or scrolling. And those fields will need scroll bars if they are not expandable. Definitely the collection name and description fields fit this category.

**Comment by astridu** [comment]
This is a considered decision bc some fields require more text than others. If the ability to expand the text field is difficult, then we can define the size of those boxes that require more space. If you can implement the drag widget, it should move vertically only; you don't have to remember the dimensions it was dragged to, but it would be nice; and it would be nice to support line breaks, but not mandatory.

**Comment by jcoyne** [comment]
@astridu I don't think it's possible to have a multi-line email (Contact email) field: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

I also don't think we want to support pressing enter in a URL field or a link title (because the former would be invalid and the latter probably won't be presented correctly)

**Comment by jcoyne** [comment]
@amyehodge since this is a "nice to have" rather than a "must have" I'm moving it to the backlog until we have all the "must haves" done.

**Comment by amyehodge** [comment]
The fact that the depositors field is not currently expandable caused me some frustration yesterday when trying to add 17 SUNets one at a time to a collection. I couldn't easily see the end of my list, or the entire list at one time, to make sure I'd gotten everyone. (Making a note here for myself about this that this request may be more important than initially anticipated.)

**Comment by jcoyne** [comment]
@amyehodge a much simpler way to fix that case in particular would be to write a ticket "The depositors field should use a textarea".  That should be a very quick fix.

**Comment by amyehodge** [comment]
Thanks @jcoyne. I'll make that one bit a new ticket.

**Comment by amyehodge** [comment]
@jcoyne and @astridu Is it possible to also get the Collection Description field here set as a text area? That would take care of the biggest problem for space on this form still. If so, I can write another ticket for that.
