### ISSUE TITLE
Create "What's changing" UI element for collections

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#968]
This is basically replicating the functionality for the work page (see #454) for the collections

https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420954309

**Comment by aaron-collier** [comment]
@amyehodge / @astridu / @jcoyne - I think we need a design for this. The current one above is based on the work editing we did last work cycle.

Also - note my comment in channel. We store the collection details in the version (name, description, etc) so we either need to change the details block on editing for this, or update the model(s) so that we store at least a description in the collection.

**Comment by amyehodge** [comment]
@astridu It looks like this should say "Version your collection".

You're definitely right -- there is some confusion here around the different descriptions. 

The description that is here
![Screen Shot 2021-05-13 at 5 35 41 PM](https://user-images.githubusercontent.com/5558511/118190811-a6c05b80-b411-11eb-951f-ced610f1283a.png)

...is a description for the collection itself, similar to the abstract field for works. This is a field that the user can version, but is NOT the same as the version description. 

So, I think what you said in the channel makes sense -- add a description field for the work proper that has the information from the field in the screen shot above and then add a collection_version field the way you do for works, to store the description entered in the "what's changing" UI element. Sounds like we are on the same page.

**Comment by aaron-collier** [comment]
Thinking through this, I think adding a version_description field makes more sense. That way the title and description can still be versioned but we can also track a version description.
