### ISSUE TITLE
A depositor should be able to order the authors

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#977]
<img width="898" alt="Screen Shot 2021-02-01 at 12 35 40 PM" src="https://user-images.githubusercontent.com/92044/106502454-ffcf3980-6489-11eb-9747-5ff490f2fbfd.png">

**Comment by jcoyne** [comment]
@astridu would you be able to develop this a bit more?

**Comment by astridu** [comment]
Sure, the explicit up/down arrows will be more accessible so I went with those. I put them on the right side, which is what I'm seeing is more common after a brief search. User can click the up arrow to move the item up one and the down arrow moves the item down one. 

@jcoyne @amyehodge I was wondering since you can't delete the first entry for some of these, do we allow the user to move the 2nd entry to the first position if there are only 2 entries? or does the reordering functionality only enable when there are at least 3 entries to reorder? 

And if we do allow the 2nd entry to become a first entry, does that one then become the one that cannot be deleted?

![image](https://user-images.githubusercontent.com/42216982/120410902-c2c86600-c308-11eb-9a34-85a894ecdb0c.png)

**Comment by jcoyne** [comment]
@astridu I think the "don't delete the top entry" was the first draft level of functionality.  At this point we can make that more complex. We can make every entry have a delete button and remove the delete button if there's only one remaining.

**Comment by amyehodge** [comment]
@jcoyne and @astridu Justin's suggestion sounds right. We definitely want them to be able to rearrange the first entry as well. I'm very excited about this!

**Comment by astridu** [comment]
If there is only 1 entry, then don't show any arrows.
If there are 2 entries, show the down arrow in the first entry, and the up arrow in the second entry. 
If there are 3+ entries, show the down arrow in the first entry, and the up and down arrows in the second and subsequent entries. 
![image](https://user-images.githubusercontent.com/42216982/120845805-267baa80-c526-11eb-9a9d-44c4c90ec104.png)
![image](https://user-images.githubusercontent.com/42216982/120846030-6fcbfa00-c526-11eb-9c5d-f99c9865f90f.png)
